### ISSUE TITLE
Replace Githack.com CDN with something else

### ISSUE THREAD

**Issue by CaoHua1203** [python-visualization/folium#1307] opened 2020-04-24 03:58 UTC
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here

folium_map.add_child(folium.plugins.MeasureControl())

folium.plugins.MousePosition().add_to(folium_map)

```
#### Problem description

Since this week, the map could not be shown as previously. There is only a blank map background, but all the markers dispear.

After tracking in html, there are the error alerts.The actions (MeasureControl and MousePosition) are not supported by the object (Map). So the JavaScript is interrupted without running smoothly.

I tried to removed the two plugins, then the markers can be shown again in the map.

Does it mean no MeasureControl or MousePosition can be used in future? Or they should be used in some other ways?

Thanks.

**Comment by Conengmo** [comment] 2020-04-24 06:32
Hi, I'm unable to replicate your issue. Both plugins work fine for me. What version of folium are you using? Please make sure you use the latest version. Also, could you share a full code snippet that replicates your issue?

**Comment by CaoHua1203** [comment] 2020-04-26 02:09
Dear Conengmo,

Many thanks for your reply. 

Here below is a sample code to show my issue.

================================================================

import folium
import folium.plugins

locations = {"BEIJING":[39.90735, 116.39125],"SHANGHAI":[31.2304,121.4738]}

folium_map = folium.Map(location=locations["BEIJING"],zoom_start=2,control_scale="True",world_copy_jump=True,no_wrap=False)

folium_map.add_child(folium.plugins.MeasureControl())

folium.plugins.MousePosition().add_to(folium_map)

folium_map.add_child(folium.LatLngPopup())

folium.CircleMarker(location=locations["BEIJING"],radius=6,color="red",fill=True).add_to(folium_map)

folium.CircleMarker(location=locations["SHANGHAI"],radius=6,color="red",fill=True).add_to(folium_map)

folium_map.save("Folium Test.html")

================================================================

The CircleMarker can not be shown. Only a blank map is left there.

While if I remove the two lines of code 
"folium_map.add_child(folium.plugins.MeasureControl())" and "folium.plugins.MousePosition().add_to(folium_map)", the marker can be shown as expected.

Thanks again for your time & attention.

**Comment by Conengmo** [comment] 2020-04-26 06:30
Just tried your code snippet and it runs without issue. The resulting map is also fully working, I tried in Firefox and Chrome. So I'm afraid the issue is on your end.

Can you check your browser console and see if there are any error messages there?

**Comment by CaoHua1203** [comment] 2020-04-26 08:43
It is so weird.

Yes, there is the error messages in my browser (MicrosoftEdge) console, "SCRIPT445: SCRIPT445: Object doesn't support this action" @ "Folium Test.html (71,13)".

The script codes @ "Folium Test.html (71,13)" are here below, it is about the MeasureControl.

If I remove the MeasureControl, a similar error message will appear, at the position of MousePosition codes. The script are also given here below.

When replying, just saw your last sentence about the plugin resources. Yes, you are right. I can not reach the url you provided.

So, maybe it is the exact reason causing my issue. Thanks so much for your kind help.

================================================================

var measure_control_779f1937d13344d6804e9164065bbd52 = new L.Control.Measure(
{"position": "topright", "primaryAreaUnit": "sqmeters", "primaryLengthUnit": "meters", "secondaryAreaUnit": "acres", "secondaryLengthUnit": "miles"});
map_5fabd2ad3ea940d1be04a54e7ee49100.addControl(measure_control_779f1937d13344d6804e9164065bbd52);

================================================================

var mouse_position_89340a674f3844fb9e1b2c50c52ba58a = new L.Control.MousePosition(
                {"emptyString": "Unavailable", "lngFirst": false, "numDigits": 5, "position": "bottomright", "prefix": "", "separator": " : "}
            );
            mouse_position_89340a674f3844fb9e1b2c50c52ba58a.options["latFormatter"] =
                undefined;
            mouse_position_89340a674f3844fb9e1b2c50c52ba58a.options["lngFormatter"] =
                undefined;
            map_5fabd2ad3ea940d1be04a54e7ee49100.addControl(mouse_position_89340a674f3844fb9e1b2c50c52ba58a);

================================================================

**Comment by Conengmo** [comment] 2020-04-26 09:18
We have another user who also experienced issues loading plugin resources: https://github.com/python-visualization/folium/issues/1305

Can I ask where you are located? Have you had issues loading other web resources as well? I'm asking because this means we might have to start using another CDN than githack.com.

Since you can't reach githack.com, can you check if this links works? https://cdn.jsdelivr.net/gh/ljagis/leaflet-measure@2.1.7/dist/leaflet-measure.min.js

**Comment by CaoHua1203** [comment] 2020-04-27 01:31
I am living in Shanghai, China.

For time being, except for this one, I did not encounter similar issue of loading other web resources.

I can reach the link you just provided.

Thanks.

**Comment by Conengmo** [comment] 2020-05-23 09:53
I changed the title, I think we have to replace the Githack CDN with some other CDN so our resources are reachable globally.

**Comment by Conengmo** [comment] 2020-05-24 08:49
@CaoHua1203 I made [a fix](https://github.com/python-visualization/folium/pull/1337), could you help by testing it? You can install it like this:

`pip install git+https://github.com/conengmo/folium.git@replace-githack-cdn`

Hopefully the measurecontrol and mouseposition plugins will work for you then. If so, I'll merge the fix.

**Comment by CaoHua1203** [comment] 2020-05-25 02:43
@Conengmo 
Hi, thanks for your modification, and the issue seems solved.
The MeasureControl & MousePosition are shown agin and work well now.
Due to some restriction on my computer, I can not install git. So I just copied the new "folium.py", "measure_control.py" & "mouse_position.py" to their directories respectively.
Thanks again for your help.

**Comment by Conengmo** [comment] 2020-05-25 07:21
Good to hear, and thanks for testing! I'll go ahead and merge the fix, it will be in the next release, probably v0.12.0.

**Closed** 2020-05-25 07:22 UTC
Labels: work in progress

**Comment by CaoHua1203** [comment] 2020-05-26 08:40
Thanks again!
Looking forward to the next release! :)
