### ISSUE TITLE
Geocoder plugin getting a 403

### ISSUE THREAD

**Issue by paoloalba** [python-visualization/folium#1988] opened 2024-08-19 17:04 UTC
I use the Geocoder plugin in my map, which happens not to work (403) when used from the .save() html file, but just on some machines. Comparing the traffic between the same map used in a jupyter notebook and the one from the file, I can only spot that the jupyter one has an Origin from the headers, while the file one is set to "null".
The problem appears only from the file version, in both Edge and Firefox.
I assume that if I would render the map within another app, e.g. Panel, the problem would not be present. Is there a way to make the file able to use the Geocoder?

**Comment by Conengmo** [comment] 2024-09-10 08:38
I'm unable to reproduce this issue unfortunately. You mentioned it only seems to happen on some machines.

Unfortunately there's not much we can do here. This Folium plugin wraps around a Javascript library: https://github.com/perliedman/leaflet-control-geocoder. Things like the HTTP requests are handled in that library. So I'm afraid you'll have to look there for a solution.

I'll close the issue since I don't think there's anything to be done in Folium. But if somebody finds out more about this, please also update us here.

**Closed by Conengmo** 2024-09-10 08:38 UTC
Labels: bug, plugin
