### ISSUE TITLE
Geojson popup content from data.json or a Pandas dataframe

### ISSUE THREAD

**Issue by oztalha** [python-visualization/folium#113] opened 2015-04-22 18:43 UTC
This is a follow up request on #102 ; In geoJSON file I only have the polygon data (and I don't want to modify the file), which I believe is the case for most of the time for the others as well. Instead, I would like to keep popup contents in other places such as a column in a pandas dataframe or in a JSON file (e.g. it would be more convenient to modify the file produced by data_out=data.json) as I would like to create maps with different popup contents but with the same layout. So, could you please extend the feature #102 so that we could be able to feed the popup content via **data_1** JSON as an alternative to **gjson_1** JSON ? Thanks !

**Comment by ocefpaf** [comment] 2015-08-04 17:22
In essence this is a duplicate of #6, right?  If not feel free to re-open it.

**Closed by ocefpaf** 2015-08-04 17:22 UTC
Labels: enhancement
