### ISSUE TITLE
Broken again: Geojson popup content not showing up 

### ISSUE THREAD

**Issue by achourasia** [python-visualization/folium#486] opened 2016-08-17 18:47 UTC
For release 0.2.1 the popup content is broken again
Original issue
https://github.com/python-visualization/folium/issues/100

**Comment by cloud05** [comment] 2016-08-18 05:00
Same here. Pop ups are not showing even with 'popupContent' in my geojson 'properties'.

**Comment by ocefpaf** [comment] 2016-08-18 10:38
Closing this as it is duplicate of https://github.com/python-visualization/folium/issues/198

**Closed by ocefpaf** 2016-08-18 10:38 UTC
