### ISSUE TITLE
Marker limits

### ISSUE THREAD

**Issue by yangyang2000** [python-visualization/folium#150] opened 2015-07-16 17:39 UTC
Is there a limit on the number of markers that can be displayed? It seems like 50k markers shouldn't be a problem in Leaflet (http://leafletjs.com/2012/08/20/guest-post-markerclusterer-0-1-released.html), but only a fraction of the markers I specify show up. If I specify the cluster option in simple_marker, none of the markers show up.

**Comment by ocefpaf** [comment] 2015-07-17 18:04
Can you send a [SSCCE](http://sscce.org/)?  I cannot reproduce that locally.

**Comment by ocefpaf** [comment] 2015-07-17 19:08
I just test 50k markers [here](http://nbviewer.ipython.org/gist/ocefpaf/c05b7a25d98747f63607) and everything works just fine.  So I am closing this.  Feel free to re-open if you find what is going on there.

Note that I did not upload the notebook with the resulst (>27megas!), so feel free to use that one as a test  there.

**Closed by ocefpaf** 2015-07-17 19:08 UTC

**Comment by yangyang2000** [comment] 2015-07-19 22:46
Thanks for the example. It seems that Folium is adding all the markers in my loop to the map. Here's the resulting html: http://s3-us-west-2.amazonaws.com/onlinereviews/leaflet/map_world.html (ignore the missing images linked in the popups have, they have not been uploaded yet). However, only a few hundred of my 65k markers are displayed on the map. Do you know if this something that is browser specific, server specific, or leaflet specific?

**Comment by ocefpaf** [comment] 2015-07-24 20:49
Not sure... and it is hard to debug/investigate this without an SSCCE.
