### ISSUE TITLE
ClickForLatLng not responding when using geopandas.explore()

### ISSUE THREAD

**Issue by Ivan-Tucker** [python-visualization/folium#1719] opened 2023-02-06 14:42 UTC
When geopandas.explore() is used to create a folium map in a Jupyter notebook, the ClickForLatLng feature does not copy data to the clipboard. The similar feature LatLngPopup() works as expected, so it seems to be specific to the ClickForLatLng feature. 

```
import geopandas as gpd 
import folium

nybb = gpd.read_file(gpd.datasets.get_path('nybb'))
map1 = nybb.explore(
     column="BoroName", # make choropleth based on "BoroName" column
     tooltip="BoroName", # show "BoroName" value in tooltip (on hover)
     tiles="CartoDB positron", # use "CartoDB positron" tiles
     cmap="Set1", # use "Set1" matplotlib colormap
     style_kwds=dict(color="black") # use black outline
    )
map1.add_child(folium.LatLngPopup())
map1.add_child(folium.ClickForLatLng(alert= True, format_str = '"[" + lat + "," + lng + "]"'))
map1
```

Regardless of where on the map I click, the data is not copied to the clipboard. 

My environment is as follows:
VS Code - 1.75.0
Jupyter - v2023.1.2000312134
Python - 3.10.5
Folium - 0.14.0
Branca - 0.6.0
GoePandas - 0.12.2

**Comment by Conengmo** [comment] 2023-02-17 11:02
I'm afraid I can't reproduce this issue, both in Jupyter Notebook and plain html. 

What browser do you use?

If you try this most minimal example, does it work?

```
from folium import Map, ClickForLatLng

m = Map()
m.add_child(ClickForLatLng())
```

Since I can't reproduce this and it seems unlikely there's something wrong with Folium, I'll close this issue. But feel free to provide more detail here, so we can see what's going on. If necessary we'll reopen.

**Closed by Conengmo** 2023-02-17 11:02 UTC

**Comment by Ivan-Tucker** [comment] 2023-02-17 12:14
The minimal example you provided does not work either. For me, the issue occurs when running a Jupyter notebook in VS Code. My code works when saved and run as a Python file in VS Code, so it seems to be specific to Jupyter.

I use Chrome, but tried other browsers before I submitted the issue. All produced the same results.

**Comment by Conengmo** [comment] 2023-02-17 12:20
Maybe it's some permission problem, that the Jupyter Notebook server doesn't have access to the clipboard or something... I don't know. I'm afraid I can't really help you further.
