### ISSUE TITLE
Chloropleth map of india based on data given

### ISSUE THREAD

**Issue by rashadkp** [python-visualization/folium#1310] opened 2020-04-24 14:04 UTC
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here
from __future__ import print_function # this line adds compatibility to python 2
import numpy as np  # useful for many scientific computing in Python
import pandas as pd # primary data structure library
from IPython.display import display
import folium
import _json
import json
from folium import TileLayer

df_can = pd.read_excel(r'C:\Users\DELL\Desktop\Book1.xlsx',
                     sheet_name='Sheet1')


india_map = folium.Map(zoom_start=2,tiles=None)
TileLayer(tiles='https://api.maptiler.com/maps/bright/{z}/{x}/{y}@2x.png?key=HmFDBGna8Uvh3s7BdfxN',name='Base Map',
    attr='<a href=https://www.maptiler.com/copyright/>© MapTiler | </a><a href=http://www.openstreetmap.org/about/>© OpenStreetMap').add_to(map)
india_geo=r'https://raw.githubusercontent.com/deldersveld/topojson/master/countries/india/india-states.json'
india_map.choropleth(
    geo_data=india_geo,
    data=df_can,
    columns=['STATE', 'COUNT'],
    key_on='feature.properties.name',
    fill_color='YlOrRd',
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name='COVID COUNT'
)
display(india_map)
india_map.save("mymap1.html")
```
#### Problem description
i written this code to display the chloropleth map of india based on the data i entered.but the resulting map is just simple world map
[this should explain **why** the current behavior is a problem and what is the expected output.]

#### Expected Output
chloropleth map of india based on data given
#### Output of ``folium.__version__``
0.5.0

**Comment by Conengmo** [comment] 2020-04-25 06:25
This seems like a dupe of #1306

**Closed by Conengmo** 2020-04-25 06:25 UTC
