### ISSUE TITLE
LayerControl defaults

### ISSUE THREAD

**Issue by matsavage** [python-visualization/folium#740] opened 2017-10-02 12:07 UTC
Currently there seems to be no way to set the layers which are shown by default in Folium

I am currently producing maps with a lot of overlays, and it looks really confusing at first, as all overlays are shown on top of each other

Would it be possible to add a method to select which layers will be displyed by default?

Many thanks

**Comment by ocefpaf** [comment] 2017-10-02 12:16
Duplicate of #606 
PRs welcomed :wink:

**Closed by ocefpaf** 2017-10-02 12:16 UTC
