### ISSUE TITLE
Folium Map Doesnt load up after geojson tooltip insertion

### ISSUE THREAD

**Issue by kp6689** [python-visualization/folium#1176] opened 2019-07-13 08:25 UTC
```python
import folium
import pandas as pd
import numpy as np
import geopandas as gpd
import fiona
import matplotlib.pyplot as plt
import seaborn as sns
from shapely.geometry import Point
from branca.colormap import linear
import random
import shapely
import geopandas

location = pd.read_csv('community.csv',encoding= "ISO-8859-1")
location = location.dropna()
location = location.reset_index(drop=True)
location.head()

from geopandas import GeoDataFrame
import json
geojson_layer = folium.GeoJson(json.load(open('Boundaries.geojson')),
                               name='geojson')
gdf1 = geopandas.read_file('Boundaries.geojson')
gdf1['area_num_1'] = gdf1.area_num_1.astype(int)
cols=['community','geometry','area_num_1']
gdf = gdf1[cols]

polygon = location
cols = ['community','latitude','longitude','arrest','domestic']
polygon = polygon[cols]
polygon_1 = pd.merge(polygon,gdf,left_on='community',right_on='area_num_1',how='left')
polygon_1 = GeoDataFrame(polygon_1,crs={'init':'epsg:4326'},geometry=gdf['geometry'])
polygon_1 = polygon_1.dropna()

map1 = folium.Map(location=[41.6,-87.5],zoom_start=12,tiles='Stamen Terrain')
#heat_data = [[row['latitude'],row['longitude']] for index, row in polygon_1.iterrows()]
minimap = plugins.MiniMap()
map1.add_child(minimap)

geoj2 = folium.GeoJson(data=polygon_1,
               name='chicago',smooth_factor=2,
                style_function=lambda x: {'color':'grey', 'fillOpacity': 0.9,'weight':0.5},
               tooltip=folium.GeoJsonTooltip(fields=['community_x', 'latitude'],
                                             aliases = ['Number of Transactions','Total People'],
                                             style="font-family: san serif;",
                                              labels=True,sticky=True),
                      highlight_function=lambda x:{'weight':0.5,'fillColor':'Red',
                                               'fillOpacity':0.4}).add_to(map1)
```

**Comment by ocefpaf** [comment] 2019-07-13 21:15
Without your data we cannot reproduce that snippet. Also, if you are on Jupyter, ypu may have to use `--NotebookApp.iopub_data_rate_limit=1000000000` sometimes to get complex HTML elements to show properly.

**Comment by kp6689** [comment] 2019-07-14 05:53
thanks for your reply, pls find the link to the files as used 

>https://we.tl/t-MSpBJNWgRv

**Comment by kp6689** [comment] 2019-07-14 06:31
Also after sorting the code a bit more in this fashion:
colormap1 = linear.Blues_09.scale(polygon_1['arrest'].min(),polygon_1['arrest'].max())
test2 = polygon_1.set_index('community_y')['arrest']
from folium import plugins
import geopandas
map1 = folium.Map(location=[41.6,-87.5],zoom_start=2,tiles='mapboxbright')
minimap = plugins.MiniMap()
map1.add_child(minimap)
geoj2 = folium.GeoJson(data=polygon_1,name='chicago',smooth_factor=2,
style_function=lambda x: {'color':'grey', 'fillOpacity': 0.9,'fillColor': colormap1(test2[x['properties']['community_y']]),
                                         'weight':0.5},                       
                     highlight_function=lambda x:{'weight':0.5,'fillColor':'Red','fillOpacity':0.4},
               
               tooltip=folium.GeoJsonTooltip(fields=['community_x','latitude','longitude','arrest','domestic','community_y'],
                                             aliases = ['community_no','latitude',
                                                        'longitude','arrest','domestic','community_name'],
                                             style="font-family: san serif"
                         ,labels=True,sticky=True
                                            )
                                         ).add_to(map1)
>> below is the error I'm encountering:
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by kp6689** [comment] 2019-07-15 07:35
[chicago.txt](https://github.com/python-visualization/folium/files/3391232/chicago.txt)

result - No map is shown

**Comment by kp6689** [comment] 2019-07-15 08:39
with the above code and by limiting the number of rows by polygon_1=polygon_1.iloc[:10]
have reached to a point where atleast minimap is being displayed, if not the main map.
screenshot below
![image](https://user-images.githubusercontent.com/52552377/61204185-23535780-a71f-11e9-9d8b-bc4d50c624b8.png)

**Comment by Conengmo** [comment] 2019-07-15 08:48
Can you try two things to help debug this?

- Save the map as an html file and open that in your browser separately?
  ```
  m = folium.Map()
  m.save('map.html')
  ```
- Check your browser Javascript console for relevant error messages. You can find it in your browsers developer tools.

**Comment by kp6689** [comment] 2019-07-15 09:02
same result, cant wade thru JS console

![image](https://user-images.githubusercontent.com/52552377/61205329-5c40fb80-a722-11e9-8d88-2c54116f83a2.png)

**Comment by kp6689** [comment] 2019-07-15 09:05
pls find data files as being used
https://we.tl/t-8rhvcXKJXC

**Comment by Conengmo** [comment] 2019-07-15 09:28
What do you mean you can't wade through the JS console?

**Comment by kp6689** [comment] 2019-07-15 10:27
Im sorry, i tried going thru the JS console, but wasnt able to locate any problem per se, your kind guidance is required!

**Comment by kp6689** [comment] 2019-07-15 10:30
regrets again, pls find the error window screenshot as asked for

![image](https://user-images.githubusercontent.com/52552377/61210269-8c8e9700-a72e-11e9-958f-52f464e91610.png)

**Comment by kp6689** [comment] 2019-07-15 16:03
`import folium
import pandas as pd
import numpy as np
import geopandas as gpd
import fiona
import matplotlib.pyplot as plt
import seaborn as sns
from shapely.geometry import Point
from branca.colormap import linear
import random
import shapely
import geopandas
from geopandas import GeoDataFrame
gdf1 = gpd.read_file('usstates.json')
#gdf1['area_num_1']=gdf1['area_num_1'].astype(int) 
gdf = GeoDataFrame(crs={'init':'epsg:4326'},geometry=gdf1['geometry'])
cols=['NAME','CENSUSAREA','STATE','geometry']
gdf = gdf1[cols]
gdf.head()`

**Comment by kp6689** [comment] 2019-07-15 16:07
change the data to : http://eric.clst.org/tech/usgeojson/
and code to>>
[usa.txt](https://github.com/python-visualization/folium/files/3393174/usa.txt)
still no display whatsoever..

**Comment by kp6689** [comment] 2019-07-16 02:39
added gdf=gdf[:25] somewhere in between and the half-souled map shows up!!

**Comment by kp6689** [comment] 2019-07-16 02:43
please suggest a way to improve browser perf before i close this issue?

**Comment by Conengmo** [comment] 2019-07-21 17:04
- You can try setting `prefer_canvas` to True: `folium.Map(prefer_canvas=True)`.
- We've heard about issues with Jupyter on Chrome before. Try using another browser, for example Firefox.
- Saving the HTML file and opening that in your browser outside of Jupyter should allow you to display more items.
- Ocefpaf already commented on changing the display limit.

Other than that there's not much to do that I know of other than limiting the things you are displaying. You could reduce the number of data points, or not use highlighting for example.

I'm closing the issue since this seems not a bug in folium, but an expected limitation.

**Closed by Conengmo** 2019-07-21 17:04 UTC
