### ISSUE TITLE
Color-bar/App

### ISSUE THREAD

**Issue by MatteoSerafino** [python-visualization/folium#1314] opened 2020-04-28 12:04 UTC
I'm having two different issues with folium. The first one is that I'm using color map in the following way:
```
    linear = cm.LinearColormap(
    ['#172E74', '#05F90B','#427024', '#F2D60E','#F90000'],
    index=[5,24,36,48,60],
    vmin=5, vmax=60)
    linear.caption = 'Time'
    m.add_child(linear)
    linear_real =   cm.StepColormap(
    ['#F9FB97','#F6F904', '#F1DB0B', '#F8524A'],
    index=[1,50,200,400],
    vmin=1, vmax=500)
    linear_real.caption = 'Cases'
    m.add_child(linear_real)

```
However in order to change the properties of them, such as position, font-size I have to do it manually from the HTML. Is there an automatic way to do it?

The second problem is that, if I Try to put the HTML on a personal page, then the timeslider bar
reduce or disappear as  you can see here:

![Time_slider](https://user-images.githubusercontent.com/43814789/80485818-62733200-895a-11ea-8c30-2f6ce6c4275c.JPG)

I'm really tried to fix it, but I could not find a solution, even though  the problem may be stupid.

**Comment by Conengmo** [comment] 2020-05-23 09:59
You're second issue is a duplicate of https://github.com/python-visualization/folium/issues/1262. That needs to be fixed.

For your first issue, you can add css to your map as follows:

```
from branca import Element

element = Element('<style>  [...]  </style>')
figure = m.get_root()
figure.header.add_child(element)
```

**Closed by Conengmo** 2020-05-23 09:59 UTC
