### ISSUE TITLE
FastMarkerCluster Inaccurate Markers

### ISSUE THREAD

**Issue by kaufmann42** [python-visualization/folium#822] opened 2018-02-14 17:21 UTC
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
m = folium.Map(
    [30.26759, -97.74299], 
    zoom_start=10
    )

stores = list(zip(df['name'].values, df['lat'].values, df['lng'].values))
# add features
for store in stores:
    folium.Marker(
        location=[float(store[1]), float(store[2])],
        popup=folium.Popup(store[0], parse_html=True),
        icon=folium.Icon(icon='home')
    ).add_to(m)

[see fig.1]

# now add the customers
customer_df = pd.read_csv('customer_addrs.csv').dropna()
customers = list(zip(customer_df['lat'].values, customer_df['lng'].values, range(len(customer_df))))
# customers
[see fig.2]

# DOES NOT WORK
from folium import plugins
plugins.FastMarkerCluster(customers).add_to(m)
m # will create these weird little groupings that don't exist in the coordinate list shown below
[see fig.3]

```
![image](https://user-images.githubusercontent.com/11468557/36217950-6e48f378-1178-11e8-86f7-0c17c7613e73.png)
**fig.1**
![image](https://user-images.githubusercontent.com/11468557/36217984-873b449e-1178-11e8-9f37-498f8d6fbee3.png)
**fig.2**
![image](https://user-images.githubusercontent.com/11468557/36218023-afa3401c-1178-11e8-92ba-f18fe2934ed9.png)
**fig.3**

#### Problem description

I'm trying to put a series of markers on a map representing stores (~20) in an area. I then want to add a MarkerCluster that allows me to show a large set (340) of customers in the area. What is happening is the coordinates that I'm providing are not being accurately displayed. As shown in the last picture something is happening where they group together in little circles instead of displaying accurately.

#### Output of ``folium.__version__``
`
Out[262]:
`'0.5.0'`

**Comment by Conengmo** [comment] 2018-02-16 08:38
In figure 3, the grouped markers on the right looks like they have the same coordinates. The plugin moves them a bit so they are all visible and connects them to the base point with small legs. This is called to 'spiderfy'. Like on this image: https://i.stack.imgur.com/tGt5U.png

Can you check if these markers indeed have the same coordinates? The spiderfy thing is expected behavior.

**Comment by kaufmann42** [comment] 2018-02-17 19:55
They do not have the same coordinates. I'll add my set of coordinates shortly.

**Comment by Conengmo** [comment] 2018-02-18 15:13
Are you sure? Because in figure 2 I already spotted a duplicate coordinate: number 5 and number 17.

**Comment by Conengmo** [comment] 2018-04-12 07:56
Closing this issue for now, let us know if you have any updates.

**Closed by Conengmo** 2018-04-12 07:56 UTC
