### ISSUE TITLE
Store the folium object In Vega style

### ISSUE THREAD

**Issue by mattijn** [python-visualization/folium#610] opened 2017-03-24 21:22 UTC
Will it be very hard to store a folium map object as a Vega Json object?

And/or can it be possible to apply a veja-json 2 folium-json object mapping, so a Vega-json object can be read and a folium/leaflet map is created.
For example the visualization description of a chloropeth map including a hover: https://vega.github.io/vega/examples/county-unemployment/

**Comment by ocefpaf** [comment] 2017-03-27 19:51
That would not be too hard. In fact the `vincent` "plugin" did that but `vincent` is an unsupported package now. Ideally we should use `altair` for that.

PRs welcomed :smile: 

PS: I am closing this as it is duplicate of https://github.com/python-visualization/folium/issues/488

**Closed by ocefpaf** 2017-03-27 19:51 UTC
