### ISSUE TITLE
TimestampedGeoJson doesn't work with dates before 1970

### ISSUE THREAD

**Issue by SFrinking** [python-visualization/folium#1273] opened 2020-03-19 11:05 UTC
I'm having a problem with TimeStampedGeoJson not displaying the timeline correctly for dates pre-1970. I get an error "Time not available" when I try it. It does work, however, when I add at least 1 date that is after 1970, but then the scale on the timeline is really fucked up. Does anyone know how to fix this?

**Comment by uli22** [comment] 2020-08-18 10:13
Can somebody confirm, that TimeStampedGeoJason not works for Dates before 1970 - I have historical dates 1700, 1882 and soon. I want to use them as a Timeslider.

**Comment by erickmattoso** [comment] 2021-08-02 01:47
Hi guys, any news here? I also have a situation like SFrinking

**Comment by ljhwang** [comment] 2021-11-15 17:49
We would also like to know if there is a solution or work around?  We get the dates to show up correctly on the timeslider but only dates after 1970 will actually display on the map.

**Comment by sddwt** [comment] 2022-05-12 09:13
is there any one cares about that :(
I guess I have to do it on my own...

**Comment by Conengmo** [comment] 2022-11-23 14:36
Duplicate of https://github.com/python-visualization/folium/issues/1205

**Closed by Conengmo** 2022-11-23 14:36 UTC
