### ISSUE TITLE
raise Value Error('Custom files must have an attribution') in folium

### ISSUE THREAD

**Issue by kananep** [python-visualization/folium#1900] opened 2024-03-12 14:20 UTC
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
# Your code here

```
#### Problem description

[this should explain **why** the current behavior is a problem and what is the expected output.]

**Comment by Conengmo** [comment] 2024-04-03 09:34
Dupe of https://github.com/python-visualization/folium/issues/1900

**Closed by Conengmo** 2024-04-03 09:34 UTC

**Comment by kananep** [comment] 2024-04-09 09:33
> Dupe of #1900

Alright. Thank you
