### ISSUE TITLE
Creating documentation latex files fails (Python 2.7)

### ISSUE THREAD

**Issue by 1kastner** [python-visualization/folium#982] opened 2018-10-12 10:50 UTC
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```shell
cd ./docs
make latex
```

#### Problem description

Instead of creating the tex files the following happens:

```shell
sphinx-build -b latex -d _build/doctrees   . _build/latex
Running Sphinx v1.8.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "XXXXXXX/.local/lib/python2.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "XXXXXXX/.local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "XXXXXXX/.local/lib/python2.7/site-packages/six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "/YYYYYYY/folium/folium/docs/conf.py", line 52, in <module>
    from folium._version import get_versions
ImportError: No module named folium._version

Makefile:99: recipe for target 'latex' failed
make: *** [latex] Error 2
```

#### Expected Output

Nice latex files which I could use for creating a PDF.

#### Output of ``folium.__version__``
     0.6.0+30.g9f648a2.dirty'

**Comment by Conengmo** [comment] 2018-10-12 12:17
Duplicate of #983, closing this one in favour of the Python 3 one.

**Closed by Conengmo** 2018-10-12 12:17 UTC
