### ISSUE TITLE
Adapt color gradient of folium.plugins.HeatMap() to branca.colormap

### ISSUE THREAD

**Issue by AndreasLuckert** [python-visualization/folium#1303] opened 2020-04-20 10:14 UTC
#### Python 3 code sample of folium.plugins.HeatMap() - implementation with colormap

```python
# Package importing
import folium
import folium.plugins as fol_plugins


# Instantiate folium base map to plot on
folium_map = folium.Map(location=coord_center_point,
                        zoom_start=zoom_level,
                        max_zoom=max_zoom,
                        tiles=mapbox_tile_URL,
                        attr='Mapbox')

## Add BRANCA colormap ##
import branca.colormap as branca_folium_cm
colormap = branca_folium_cm.linear.Blues_05.scale(z_min, z_max)
colormap.caption = "Bla bla"  # how do I change fontsize and color here?
folium_map.add_child(colormap)

# Prepare gradient dictionary according to the example like {0.4: ‘blue’, 0.65: ‘lime’, 1: ‘red’}
gradient_dict = {}
# Get the index values and colors from the just created branca-colormap
# NOTE: colors are RGBA-vectors, like "(0.9372549019607843, 0.9529411764705882, 1.0, 1.0)":
for ind_val, c in zip(colormap.index, colormap.colors):
    # Create gradient dictionary for heatmap on the fly
    gradient_dict[ind_val] = c

# Resulting gradient dict in my case:
# {1.4117859851611496e-05: (0.9372549019607843, 0.9529411764705882, 1.0, 1.0), 0.00247235752568163: (0.7411764705882353, 0.8431372549019608, 0.9058823529411765, 1.0), 0.004930597191511649: (0.4196078431372549, 0.6823529411764706, 0.8392156862745098, 1.0), 0.007388836857341667: (0.19215686274509805, 0.5098039215686274, 0.7411764705882353, 1.0), 0.009847076523171685: (0.03137254901960784, 0.3176470588235294, 0.611764705882353, 1.0)}

# Overlay the heatmap data on top of the previously instantiated folium basemap
fol_plugins.HeatMap(data=zip(y, x, z),
                    name=titlestr,
                    min_opacity=min_alpha_opacity,
                    max_zoom=max_zoom,
                    radius=radius,
                    gradient=gradient_dict,  # insert gradient dict
                    blur=blur).add_to(folium_map)
```
#### Problem description

The data points don't even show up on the output graphic/map.
Is this due to the fact that my gradient-dict is passed with RGBA-color-values instead of bold color-strings like "blue", "green", etc.?
If I don't get the color-ranges adapted to the colormap plotted alongside the actual map, my datapoints will always be displayed in the default manner (which is something like from blue over yellow to red).

As an aside, I would also like to know how to change font-size and color of the branca.colormap.caption and the index-ticklabels.
It is always displayed in black with a default fontsize. Sometimes, this isn't really visible against the current map background.

#### Expected Output

The datapoints of my HeatMap are plotted respecting the same colormap as I created via branca.colormaps. I thought this would be possible via the gradient-parameter of folium.plugins.HeatMap().

Moreover, I would like to change the fontsize and -color of the branca.colormap.caption.

#### Output of ``folium.__version__``
'0.10.1'

**Comment by markhudson42** [comment] 2020-08-18 09:26
Hello,

I think that the issue is that the colour information needs to be passed to the gradient dictionary in a different way from how you are passing it.

You are passing the `c` variable directly, which is a tuple like `(0.9372549019607843, 0.9529411764705882, 1.0, 1.0)`, but I have found that I can get the colour scale to work if I store strings like `rgb(0,0,255)` in the dictionary.

Your code sample did not define all of the data you are using, so I have invented some for those items that were not provided, and I have changed the way in which data are stored in your gradient_dict. Also note that I am using the latest master branch version of folium because I know from other issues that there is a problem with the scaling in the latest release. However, the issue in the latest release (0.11.0) is not the cause of your current problem.

Here is the code that I have made from your code - the important bit is the way that the gradient_dict is made:

```python
# Package importing
import folium
import folium.plugins as fol_plugins

# set some values for undefined variables
coord_center_point = (51.5, 0.0)
zoom_level = 10
max_zoom = 18

# Instantiate folium base map to plot on
# I have changed this to use OpenStreetMap tiles (the default)
folium_map = folium.Map(location=coord_center_point,
                        zoom_start=zoom_level,
                        max_zoom=max_zoom,
                        attr='Mapbox')

## Add BRANCA colormap ##
import branca.colormap as branca_folium_cm

# these min and max values I inferred from your gradient dict
z_min = 1.4117859851611496e-05
z_max = 0.009847076523171685

colormap = branca_folium_cm.linear.Blues_05.scale(z_min, z_max)
colormap.caption = "Bla bla"  # how do I change fontsize and color here?

folium_map.add_child(colormap);

# Prepare gradient dictionary according to the example like {0.4: ‘blue’, 0.65: ‘lime’, 1: ‘red’}
gradient_dict = {}

# Get the index values and colors from the just created branca-colormap
# NOTE: colors are RGBA-vectors, like "(0.9372549019607843, 0.9529411764705882, 1.0, 1.0)":
for ind_val, c in zip(colormap.index, colormap.colors):
    # Create gradient dictionary for heatmap on the fly
    r, g, b, a = c
    gradient_dict[ind_val] = f"rgba({r},{g},{b},{a})"

print(gradient_dict)

# make some data for display
import numpy as np # for random numbers
x = [coord_center_point[1] + np.random.random()/10 - 0.1 for i in range(100)]
y = [coord_center_point[0] + np.random.random()/10 - 0.1 for i in range(100)]
z = [np.random.randint(0, 100) for i in range(100)]

titlestr = 'this is my heatmap example'
min_alpha_opacity = 0.1
radius = 5
blur = 5

# Overlay the heatmap data on top of the previously instantiated folium basemap
fol_plugins.HeatMap(data=zip(y, x, z),
                    name=titlestr,
                    min_opacity=min_alpha_opacity,
                    max_zoom=max_zoom,
                    radius=radius,
                    gradient=gradient_dict,  # insert gradient dict
                    blur=blur).add_to(folium_map)

folium_map
```

The end result of running my code in a Jupyter notebook is:

![image](https://user-images.githubusercontent.com/17765609/90496023-33691200-e13d-11ea-94b3-fb2d045bedfa.png)

I hope this is useful for you.

Mark.

**Comment by AndreasLuckert** [comment] 2020-10-21 13:02
Hey Mark,

thanks again for your help.
Apart from your solution, I've found an [own one](https://stackoverflow.com/a/63533605/12298276).

It should also work with HEX-colors.

**Comment by Conengmo** [comment] 2020-10-21 15:29
Thanks Mark, and Andreas for reporting back on this. I guess that means we can close this.

**Closed by Conengmo** 2020-10-21 15:29 UTC
