### ISSUE TITLE
conflict of TimestampedGeoJson and popup with Vega

### ISSUE THREAD

**Issue by Kittyuzu1207** [python-visualization/folium#1426] opened 2020-12-12 13:32 UTC
Hi, thanks for such an excellent tool. I have encountered a problem and hope you can help us~
When we use a popup with simple text, our TimestampedGeoJson layer works well. But when we change the popup with Vega, our html can not show any of these things. When we remove TimestampedGeoJson layer, the popup with Vega works well.
In a word, they can work separately, but when we put them together, it crashes.  Have I missed something? Can anyone helps us to solve this conflict? Thanks a lot!!😊

**Comment by matkoniecz** [comment] 2021-06-28 08:48
Can you produce some minimal code sample reproducing this issue?

See https://stackoverflow.com/help/minimal-reproducible-example

To quote the current issue template:

> Include a code snippet that produces your bug. Make it standalone, we should be able to run it.
> Include a data sample or link to your data if necessary to run the code

```
**Environment (please complete the following information):**
 - Browser [e.g. chrome, firefox]
 - Jupyter Notebook or html files?
 - Python version (check it with `import sys; print(sys.version_info)`)
 - folium version (check it with `import folium; print(folium.__version__)`)
 - branca version (check it with `import branca; print(branca.__version__)`)
```

**Comment by Conengmo** [comment] 2022-11-18 14:44
I'll close this issue, since the use case is a bit too complex to support ourselves.

**Closed by Conengmo** 2022-11-18 14:44 UTC
