### ISSUE TITLE
Map won't display if popup field has certain characters. 

### ISSUE THREAD

**Issue by fabhlc** [python-visualization/folium#853] opened 2018-04-29 22:11 UTC
#### Map won't display if popup field contains single quotation marks (escape) or apostrophe. Code runs fine but output is an empty box.

```python
Toronto = [43.653409, -79.384079]
map = folium.Map(location= Toronto,
                 tiles = 'Stamen Terrain')

folium.Marker(location=[43.653409, -79.384079],
              popup=str('This won\'t work')).add_to(map)
folium.Marker(location=[43.653409, -79.384079],
              popup=str('This works fine')).add_to(map)

```
#### Once they are removed, my leaflet map shows up perfectly (Jupyter Notebook). Is there a fix for this?

Running on version 0.5.0

**Comment by Conengmo** [comment] 2018-04-30 06:04
A popup expects a valid html string. An apostrophe is not valid html, and escaping it in Python is not the same as escaping it in html. Html needs these `&#39;` kind of special character declarations.

If you have some special characters that need to be html-escaped, you can use the `parse_html=True` option in Popup. Check out the examples here:
https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Popups.ipynb

This is a duplicate of #850 by the way, so please add any discussion there.

**Closed by Conengmo** 2018-04-30 06:04 UTC
