### ISSUE TITLE
Introducing a parameter to adjust legend positions

### ISSUE THREAD

**Issue by anuraghuram** [python-visualization/folium#1348] opened 2020-06-05 01:21 UTC
Hello all, is there a feature to adjust legend positions (e.g. 'top', 'bottom' 'left', 'right') for choropleth maps? Currently, they are displayed horizontally across the top of the map. Additionally, I think it would be useful to have some sort of a 'minimisable' option (similar to the layer controls feature), so you can toggle to hide legends. 

These would be beneficial in cases where you have multiple legends overcrowding the visual (see personal example below and code [here](https://github.com/anuraghuram/nypd/blob/master/mapviz.py))

**Comment by anuraghuram** [comment] 2020-06-05 01:25
Is there a feature to adjust legend positions for choropleth maps? Currently, they are displayed horizontally across the top of the map. Two parameters I think would be useful are:

1. Custom positioning of legends (e.g. 'top', 'bottom' 'left', 'right')
2. Integrate a 'minimizable' option (similar to the layer controls feature), so you can hide multiple legends on maps to avoid overcrowding the visual.

**Comment by Conengmo** [comment] 2022-11-23 14:26
Partial duplicate of https://github.com/python-visualization/folium/issues/1605

Also related to https://github.com/python-visualization/folium/issues/1079

I'm closing this one so we don't have multiple open issue on roughly the same topic.

**Closed by Conengmo** 2022-11-23 14:26 UTC
Labels: enhancement
