### ISSUE TITLE
Folium Map on NBviewer?

### ISSUE THREAD

**Issue by oztalha** [python-visualization/folium#101] opened 2015-04-17 13:07 UTC
I would like my map to be shown inside NBviewer just as in the case of [this example](http://nbviewer.ipython.org/github/urschrei/Geopython/blob/master/convert_folium.ipynb) (`Out[18]`) or [that one](http://nbviewer.ipython.org/gist/bburky/7763555/folium-ipython.ipynb) (`Out[4]`) , but [getting a no-color map](http://nbviewer.ipython.org/github/oztalha/GeoInfluence/blob/master/analysis/Desc%20Stats%20of%20the%20Challengers.ipynb?flush_cache=true) (`Out[4]`) or a 404 error instead (`Out[36]`). What might be causing mine to fail, my code is identical to the working examples.

Note: Unlike nbviewer, I can see the map correctly inside my local IPYNB viewer:
![IPYNB on localhost][1]

  [1]: http://i.stack.imgur.com/Cgymz.png

Note, this question is also asked in SO: http://stackoverflow.com/questions/29687366/folium-map-on-nbviewer

**Comment by ocefpaf** [comment] 2015-04-17 13:10
Can you send the nbviewer link?  So we can see how you are displaying the map.  Also, are you uploading the GeoJSON to the same repository?  Or loading it online from somewhere?

**Comment by oztalha** [comment] 2015-04-17 13:45
sure, the link was inside my post indeed, more explicitly here it is: http://nbviewer.ipython.org/github/oztalha/GeoInfluence/blob/master/analysis/Desc%20Stats%20of%20the%20Challengers.ipynb?flush_cache=true

**Comment by ocefpaf** [comment] 2015-04-17 13:47
OK.  Closing them.

**Comment by birdage** [comment] 2015-04-17 13:49
i can see the geojson ok here https://github.com/oztalha/GeoInfluence/blob/master/analysis/us_states.geojson

**Comment by birdage** [comment] 2015-04-17 14:02
the issue is gjson_1 is undefined in the generated map html here https://github.com/oztalha/GeoInfluence/blob/master/analysis/gov_share.html#L102
so the geojson is not displayed

**Comment by ocefpaf** [comment] 2015-04-17 14:02
@oztalha  The GeoJSON is there and it is OK.  The problem is that you are using the `embed_map` instead `inline_map`.  See the difference between them here:

"http://nbviewer.ipython.org/github/ocefpaf/GeoInfluence/blob/master/analysis/Desc%20Stats%20of%20the%20Challengers.ipynb"

inline is messy and all the HTML will be in the notebook.  Embed is more "elegant", but you need to serve all the data for the HTML online as relative links or you will face that issue.  Also, that function is using (`src="files/{path}"`), which I am unsure works for the latest nbviewer.

**Closed** 2015-04-17 14:02 UTC

**Comment by oztalha** [comment] 2015-04-17 14:06
Thanks for confirming, I tested embed with `src="files/{path}"` too but they also fail (see `Out[34]` and `Out[36]`). BTW, I'm on Windows (Winpython) and git bash replaces LF with CRLF when adding files. Suspected if git somehow corrupts the file, so moved the html file to a webserver, but it looks ok : http://talhaoz.com/geoinfluence/map.html

**Comment by birdage** [comment] 2015-04-17 14:13
i grabbed the html file served it locally and grabbed the geojson and removed the style (just cause) and i get it to render in leaflet, dont know what this proves other than you can plot it. more digging required!

![screen shot 2015-04-17 at 10 12 33 am](https://cloud.githubusercontent.com/assets/547228/7203685/5b12aa46-e4ea-11e4-8df9-4b339d08e8cd.png)

**Comment by oztalha** [comment] 2015-04-17 14:35
Thanks, with a clear test, this works now ! http://nbviewer.ipython.org/github/oztalha/GeoInfluence/blob/master/analysis/Folium%20Notebook%20Test.ipynb

**Comment by birdage** [comment] 2015-04-17 15:11
No worries glad we could help!

**Comment by jilljenn** [comment] 2016-02-04 00:34
Thanks for this notebook using `create_map`, it helped.
