### ISSUE TITLE
MarkerCluster and FeatureGroup don't work properly together. 

### ISSUE THREAD

**Issue by BigDomi** [python-visualization/folium#809] opened 2018-01-06 18:07 UTC
```python

    import pandas as pd
    import folium
    from folium.features import CustomIcon
    from folium.plugins import MarkerCluster
    
    df1 = pd.read_csv("/home/dominik/projekt/results/pkobp.csv")
    df2 = pd.read_csv("/home/dominik/projekt/results/pekao.csv")
    
    logo_PKOBP = 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Logotyp_PKO_BP.svg'
    logo_PEKAO = 'https://upload.wikimedia.org/wikipedia/commons/e/ee/Bank_Pekao_SA_Logo_%282017%29.svg'
    
    frames = [df1, df2]
    
    locationlist1 = df1[["Szerokość","Długość"]].values.tolist()
    locationlist2 = df2[["Szerokość","Długość"]].values.tolist()
    
    m = folium.Map(location=[52.2138, 20.9795], zoom_start=12, control_scale=True)
    
    pkobp_layer = folium.FeatureGroup(name="PKO BP SA")
    marker_cluster = MarkerCluster().add_to(pkobp_layer)
    for point in range(len(locationlist1)):
        PKOBP = folium.Marker(locationlist1[point], icon=CustomIcon(logo_PKOBP, icon_size=(40, 40))).add_to(marker_cluster)
    
    pekao_layer = folium.FeatureGroup(name="PEKAO SA")
    marker_cluster = MarkerCluster().add_to(pekao_layer)
    for point in range(len(locationlist2)):
        PEKAOSA = folium.Marker(locationlist2[point], icon=CustomIcon(logo_PEKAO, icon_size=(150, 22))).add_to(marker_cluster)
    
    m.add_child(pkobp_layer)
    m.add_child(pekao_layer)
    
    m.add_child(folium.map.LayerControl())
    
    m.save('/home/dominik/mapa1.html')

```
#### Problem description

I can't use the MarkerCluster and LayerControl together. MarkerCluster groups separately the markers from PKOBP and PEKAOSA. 

1. Can someone tell me what is wrong in my code?
2. Is it possible to change colors in MarkerCluster?

#### Expected Output
1. I would like the markers to be grouped together. (the most important)
2. If possible, I would like to change the colors, increase the number of shades.

#### Output of ``folium.__version__``
print(folium.__version__)
0.5.0

**Comment by Conengmo** [comment] 2018-01-09 20:42
I'm not sure I understand your problem. You want to cluster all the markers together? Then how about putting all your markers in a single  `MarkerCluster`? Also, you don't need a `FeatureGroup` when you're already using a `MarkerCluster`. For example:

```
import folium.plugins

m = folium.Map(location=[0, 0], zoom_start=2)
lats = [37.25715519, -31.72884313, -75.27080391, 50.30897559]
lons = [167.20482296, 23.5310324, 164.47413453, 26.87409742]

cluster = folium.plugins.MarkerCluster().add_to(m)
for i in range(0, 4):
    folium.Marker(location=[lats[i], lons[i]], popup=str(i)).add_to(cluster)

folium.LayerControl(collapsed=False).add_to(m)
m.save('map.html')
```

About colors: the `MarkerCluster` has customization options for the icons, the popups and the cluster icons. Check out the examples in the example gallery:
http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/MarkerCluster.ipynb

**Comment by Conengmo** [comment] 2018-04-12 07:53
Closing the issue since the problem is not clear. Let us know if you have any updates.

**Closed by Conengmo** 2018-04-12 07:53 UTC

**Comment by dspyrhsu** [comment] 2018-06-19 09:19
Hi guys, first of all: thanks for the awesome work on folium! 

Now to the issue: I have this as well and let me explain what I am trying to achieve:
a) Using MarkerCluster, I am hoping to avoid overloading the map with markers on certain zoom levels - works fine by itself
b) Using FeatureGroup with LayerControl, I am hoping to be able to select only markers of a certain type - again: works well by itself

By combining the two, I was hoping to be able to have all (active) markers in one cluster while being able to choose the active groups via LayerControl. This does not work.

What does work is to put the markers into different marker clusters, but then each of those has its own count for the different zoom levels - not quite what I was hoping for, but still pretty awesome.

Still, the attached screenshot should illustrate the "problem":
![cluster_group_problem](https://user-images.githubusercontent.com/26599081/41588533-59f2099a-73b2-11e8-894d-2625db79b13f.png)

So, the gray cloud icon is well within the area of the nearby cluster (of cadetblue ok-signs). Ideally, I would want it to be part of the cluster.

**Comment by dspyrhsu** [comment] 2018-06-19 17:46
Ok, thanks @Conengmo , I will give that a try. I installed folium from master last weekend, so I should be fine. I will report back after I tried that out.

**Comment by dspyrhsu** [comment] 2018-06-19 18:02
@Conengmo , you were right, that is exacly what I was looking for and it works the way I had hoped! Thanks to you and all the other contributors!

**Comment by tanthiamhuat** [comment] 2018-10-20 12:37
I like to check for that MarkerCluster, we see those number less than 10 would be green in color and 10 or greater would be orange in color. Is this already fixed? How can we change its color on a custom basis? say I have 3 groups of clusters (8,10 and 29) inside each cluster, and I want those 3 groups of clusters to be of 3 different colors. thanks.

**Comment by pabm1808** [comment] 2020-09-10 18:40
@dspyrhsu Hi! I am having the same troblue, would you be so kind to share the code you used at end? Thanks a lot in advance!

**Comment by BigDomi** [comment] 2020-09-10 18:55
Hi,

Hi,
You can see my final code at this link
https://nbviewer.jupyter.org/urls/hugedot.pl/projekt_studia/projekt/wizualizacja/mapa.ipynb
I hope you will find it useful.

Best regards,
Dominik

W dniu czw., 10.09.2020 o 20:41 pabm1808 <notifications@github.com>
napisał(a):

**Comment by pabm1808** [comment] 2020-09-10 19:09
Man it worked perfectly! Thank you so much!

**Comment by BigDomi** [comment] 2020-09-10 19:10
No problem.

W dniu czw., 10.09.2020 o 21:09 pabm1808 <notifications@github.com>
napisał(a):
