### ISSUE TITLE
Plugin for Leaflet.Control.Layers.Tree

### ISSUE THREAD

**Issue by rosshug** [python-visualization/folium#1490] opened 2021-07-17 09:10 UTC
I have a hierarchical set of layers and would like be able to select the layers in a control with a collapsible tree structure. 

There is  a Leaflet plugin that appears to do what I would like, Leaflet.Control.Layers.Tree, example below. See 
[Leaflet.Control.Layers.Tree ](https://github.com/jjimenezshaw/Leaflet.Control.Layers.Tree )

Would it be possible for someone to create a folium plugin wrapper for this Leaflet plugin please. I would attempt this myself but I do not have any experience with JavaScript, but I can help in any other way, e.g. help make a PR.

![example](https://user-images.githubusercontent.com/57917387/126032205-a14acc42-0054-4761-b3ec-2d0865dadb61.jpg)

**Comment by junholv** [comment] 2022-03-31 09:05
No solution yet ?

**Comment by Conengmo** [comment] 2022-11-18 11:39
Duplicate of https://github.com/python-visualization/folium/issues/1490

**Closed by Conengmo** 2022-11-18 11:39 UTC
