### ISSUE TITLE
TypeError: Object of type 'int64' is not JSON serializable

### ISSUE THREAD

**Issue by youngminpark2559** [python-visualization/folium#1208] opened 2019-09-20 21:23 UTC
#### Please add a code sample or a nbviewer link, copy-pastable if possible

I get `TypeError: Object of type 'int64' is not JSON serializable` error  

Working case (same code but without using for loop)
```python
# ================================================================================
import folium
import pandas as pd
import numpy as np

map = folium.Map(location=[37.350596,127.1080578], zoom_start=14)

d={'lat':[37.352794,37.364229,37.334325,37.336666,37.330313],
   'lng':[127.115063,127.121404,127.088905,127.114598,127.109283],
   '점수':[100,40,20,10,120]}
df=pd.DataFrame(d)

folium.CircleMarker([37.352794,127.115063], radius=100, color='#3186cc', fill_color='#3186cc').add_to(map)
folium.CircleMarker([37.364229,127.121404], radius=40, color='#3186cc', fill_color='#3186cc').add_to(map)
folium.CircleMarker([37.334325,127.088905], radius=20, color='#3186cc', fill_color='#3186cc').add_to(map)
folium.CircleMarker([37.336666,127.114598], radius=10, color='#3186cc', fill_color='#3186cc').add_to(map)
folium.CircleMarker([37.330313,127.109283], radius=120, color='#3186cc', fill_color='#3186cc').add_to(map)

map.save("/mnt/external_disk/Map_chart/main2.html")
```

Not working case (same code but with using for loop)
```python
# ================================================================================
import folium
import pandas as pd
import numpy as np

map = folium.Map(location=[37.350596,127.1080578], zoom_start=14)

d={'lat':[37.352794,37.364229,37.334325,37.336666,37.330313],
   'lng':[127.115063,127.121404,127.088905,127.114598,127.109283],
   '점수':[100,40,20,10,120]}
df=pd.DataFrame(d)

for n in df.index:
  folium.CircleMarker([df['lat'][n], df['lng'][n]], radius=df['점수'][n], color='#3186cc', fill_color='#3186cc').add_to(map)

map.save("/mnt/external_disk/main2.html")
```
#### Problem description
Error message  
```
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    map.save("/mnt/external_disk/Companies/B_Link/Project_code/Hopital_doc_app/Map_chart/main2.html")
  File "/home/young/anaconda3/envs/py36_chart_b/lib/python3.6/site-packages/branca/element.py", line 169, in save
    html = root.render(**kwargs)
  File "/home/young/anaconda3/envs/py36_chart_b/lib/python3.6/site-packages/branca/element.py", line 321, in render
    child.render(**kwargs)
  File "/home/young/anaconda3/envs/py36_chart_b/lib/python3.6/site-packages/folium/folium.py", line 370, in render
    super(Map, self).render(**kwargs)
  File "/home/young/anaconda3/envs/py36_chart_b/lib/python3.6/site-packages/branca/element.py", line 633, in render
    element.render(**kwargs)
  File "/home/young/anaconda3/envs/py36_chart_b/lib/python3.6/site-packages/branca/element.py", line 629, in render
    figure.script.add_child(Element(script(self, kwargs)),
  File "/home/young/anaconda3/envs/py36_chart_b/lib/python3.6/site-packages/jinja2/runtime.py", line 575, in __call__
    return self._invoke(arguments, autoescape)
  File "/home/young/anaconda3/envs/py36_chart_b/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 110, in _invoke
    return original_invoke(self, arguments, autoescape)
  File "/home/young/anaconda3/envs/py36_chart_b/lib/python3.6/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 26, in macro
  File "/home/young/anaconda3/envs/py36_chart_b/lib/python3.6/site-packages/jinja2/filters.py", line 1078, in do_tojson
    return htmlsafe_json_dumps(value, dumper=dumper, **options)
  File "/home/young/anaconda3/envs/py36_chart_b/lib/python3.6/site-packages/jinja2/utils.py", line 565, in htmlsafe_json_dumps
    rv = dumper(obj, **kwargs) \
  File "/home/young/anaconda3/envs/py36_chart_b/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/young/anaconda3/envs/py36_chart_b/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/young/anaconda3/envs/py36_chart_b/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/young/anaconda3/envs/py36_chart_b/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'int64' is not JSON serializable
```

#### Expected Output
HTML file

#### Output of ``folium.__version__``
```
print("folium.__version__",folium.__version__)
0.10.0
```

**Comment by Conengmo** [comment] 2019-09-21 06:42
Hi @youngminpark2559, it seems the issue is with the value you pass to the ‘radius’ argument. Folium doesn’t convert it to a vanilla float, so that’s why you get that error.

You can fix this by converting it to a vanilla float when you pass it. E.g. ‘radius=float(pandasvalue)’

At the moment I don’t think we’ll change folium to cast all option arguments to vanilla types. That would require quite a bit of code to register the type of each argument. So I’m closing this issue. But this is not a fixed opinion so anyone feel free to bring other arguments or ideas on this.

**Closed by Conengmo** 2019-09-21 06:42 UTC
