### ISSUE TITLE
Custom Markers only work with URLs

### ISSUE THREAD

**Issue by nanodan** [python-visualization/folium#672] opened 2017-08-24 14:39 UTC
It seems that custom markers only work with URLs and not local image files.

**This works:**

```python
icon = folium.features.CustomIcon('http://www.pngall.com/wp-content/uploads/2016/05/Iron-Man.png', icon_size=(50,50))
folium.Marker([43, -79],
              popup='Iron Man',
              icon=icon
              ).add_to(geo_map)

```
**This does not work:**

```python
icon = folium.features.CustomIcon('Iron-Man.png', icon_size=(50,50))
folium.Marker([43, -79],
              popup='Iron Man',
              icon=icon
              ).add_to(geo_map)
```

**Comment by ocefpaf** [comment] 2017-09-18 13:52
If the `Iron-Man.png` served along side the map? If not It won't work. If true and it does not work we have a bug.

**Comment by ocefpaf** [comment] 2017-09-18 14:00
I can confirm everything works as expected, closing this.

![screenshot from 2017-09-18 10-56-05](https://user-images.githubusercontent.com/950575/30545509-33a7ad28-9c60-11e7-888a-8c370cf7ff1b.png)

Maybe we could add a self-contained version that would encode the `image` in the HTML. I do have a goal to do that for everything in `folium` in a consistent way, but it will take a while.

If you want to send a PR to solve that for icons take a look at the `ImageOverlay` plugin and try to implement something along those lines.

**Closed by ocefpaf** 2017-09-18 14:00 UTC

**Comment by maxakaplan** [comment] 2018-02-20 07:18
I am having the same problem as nanodan. The first two do not work. whether it's in the same directory or a direct path. The url option works fine though. Apologies for my ignorance if there is an easy fix.

![image](https://user-images.githubusercontent.com/35230920/36411475-ae88eece-15ca-11e8-9d0f-9ea6192d2177.png)
```
icon = CustomIcon(icon_image = 'akron.png', icon_size=(30, 30))
marker = folium.Marker(location=(39.50, -98.35), icon=icon).add_to(map1)
```
```
icon = CustomIcon(icon_image = r'C:\Users\maxak\1python\akron.png', icon_size=(30, 30))
marker = folium.Marker(location=(39.50, -98.35), icon=icon).add_to(map1)
```
```
icon = CustomIcon(icon_image = r'https://upload.wikimedia.org/wikipedia/commons/4/41/Akron_Z_logo_2015.png', icon_size=(30, 30))
marker = folium.Marker(location=(39.50, -98.35), icon=icon).add_to(map1)
```

**Comment by dvu4** [comment] 2018-05-19 08:32
this code will work with local image file.

`import base64

encoded = base64.b64encode(open('Iron-Man.png', 'rb').read())
decoded = base64.b64decode(encoded)
icon_url = BytesIO(decoded)

icon = folium.features.CustomIcon(icon_url, icon_size=(50,50))
folium.Marker([43, -79],
              popup='Iron Man',
              icon=icon
              ).add_to(geo_map)`

**Comment by Conengmo** [comment] 2018-11-15 07:47
> but for list of markers, the code only shows the first icon. :(

This has come up in #744 as well. Though it is expected behavior at the moment that an icon has to be created for each marker, PR's to improve on this are welcome.

**Comment by nathan3leaf** [comment] 2019-02-23 01:03
I tried @dvu4 suggestion but it results in a TypeError: Object of type 'BytesIO' is not JSON serializable

Is there a better method for achieving this, or are custom icons still not supported?

**Comment by davidolmo** [comment] 2019-02-23 12:19
@nathan3leaf please paste the full traceback. I think I faced that error too. Let's see if I can help you

**Comment by nathan3leaf** [comment] 2019-02-23 15:43
```
Traceback (most recent call last):
  File "C:\Users\natha\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\natha\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/natha/Dropbox/PYTHON_PROJECTS/analysisSuite.py", line 13453, in runAnalysis
    self.createInteractiveMap(centerName=sites.text(), coords=[lat, lon])
  File "C:/Users/natha/Dropbox/PYTHON_PROJECTS/analysisSuite.py", line 12556, in createInteractiveMap
    MAPPING().getInteractiveMap(centerName=centerName, coords=[lat, lon], layers=layers, output=False)
  File "C:/Users/natha/Dropbox/PYTHON_PROJECTS/analysisSuite.py", line 10994, in getInteractiveMap
    clientIcon = folium.features.CustomIcon(icon_url, icon_size=(50, 50))
  File "C:\Users\natha\AppData\Local\Programs\Python\Python36-32\lib\site-packages\folium\features.py", line 1146, in __init__
    self.icon_url = image_to_url(icon_image)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python36-32\lib\site-packages\folium\utilities.py", line 102, in image_to_url
    url = json.loads(json.dumps(image))
  File "C:\Users\natha\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python36-32\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python36-32\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\natha\AppData\Local\Programs\Python\Python36-32\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'BytesIO' is not JSON serializable
```
Thank you @davidolmo your help is very much appreciated.

**Comment by davidolmo** [comment] 2019-02-26 02:06
Ok I see. It seems like some code in Folium was changed recently and the utility function that parses images for CustomIcon (image_to_url) no longer supports BytesIO format in the current version. However, it **supports the path!** (so it will transform the file automatically to Bytes for you).  What I did is directly pass the path of the image:

`icon_path = r"C:\some_path\icon.png"`
`icon = folium.features.CustomIcon(icon_image=icon_path ,icon_size=icons_size)`

`marker=folium.Marker([row["coord"].y,row["coord"].x],popup=popup,icon=icon).add_to(feature_groups[alert_icon_name])`

**Comment by nathan3leaf** [comment] 2019-02-28 05:40
@davidolmo well, you are correct. I was able to make some modifications using the method you posted and it's working perfectly. Thanks for the helpful info!

**Comment by sahanaraguram2000** [comment] 2020-12-03 03:48
thank you @davidolmo this really helped me.....

**Comment by nirvannar** [comment] 2021-07-29 18:35
Thanks - I modified this code.  It helped so much!!

**Comment by ivankeller** [comment] 2022-09-10 22:33
Just an additional remark that could help if like me you have to add several markers with the same custom icon you have to re-instantiate `icon` for each marker you add. , 
For example if you do a loop, put the `icon = ...` statement inside the loop.  

Following the example above:
DO:
```
for row in my_rows:
    icon_path = r"C:\some_path\icon.png"
    marker=folium.Marker([row["coord"].y,row["coord"].x],popup=popup,icon=icon).add_to(feature_groups[alert_icon_name])
```

DON'T DO:
```
icon_path = r"C:\some_path\icon.png"
for row in my_rows:
    marker=folium.Marker([row["coord"].y,row["coord"].x],popup=popup,icon=icon).add_to(feature_groups[alert_icon_name])
```
It won't work.  
It took me some time for me to understand it, maybe because I'm new to Folium.

**Comment by traits** [comment] 2023-02-04 11:34
How do I get this to work with svg files?
