### ISSUE TITLE
HeatMapTime Time Slider broken styling

### ISSUE THREAD

**Issue by ow-wow-wang** [python-visualization/folium#1262] opened 2020-02-13 04:16 UTC
Link to site: https://aowangdrexel.github.io/ceres/website/map.html
Link to repo: https://github.com/AoWangDrexel/ceres
Link to Python code: https://github.com/AoWangDrexel/ceres/blob/master/map_data/map.py
```python
HeatMapWithTime(formatted[0], formatted[1]).add_to(m)

```
#### Problem description
When using the HeatMapWithTime pluggin, the time slider works on my localhost, but once I started hosting with Github, the slider started to have graphical issues. The slider becomes vertical and the words for the buttons all scrunch down to the bottom of the screen.

![Screen Shot 2020-02-12 at 11 10 29 PM](https://user-images.githubusercontent.com/49734116/74400920-8c9e6480-4ded-11ea-90a7-b7f78b776cb6.png)

#### Expected Output
![Screen Shot 2020-02-12 at 11 10 42 PM](https://user-images.githubusercontent.com/49734116/74400937-9a53ea00-4ded-11ea-9cb1-8527868f3ed6.png)

**Comment by Conengmo** [comment] 2020-05-23 10:02
I've seen this issue before, but cannot reproduce it at the moment. I'll keep this issue open though because I don't think it has been fixed entirely.

**Comment by ow-wow-wang** [comment] 2020-05-23 14:35
The problem was eventually solved by @blextar. I emailed him and he mentioned how Github doesn't handle the external CSS accessed through HTTP well, instead of HTTPS. So he manually changed the links 

So he replaced:
<img width="1152" alt="Screenshot 2020-02-15 at 10 54 31" src="https://user-images.githubusercontent.com/49734116/82733307-f8dc0e80-9ce0-11ea-89df-293ab6a4301e.png">

With: 
<img width="1151" alt="Screenshot 2020-02-15 at 10 55 05" src="https://user-images.githubusercontent.com/49734116/82733302-eb268900-9ce0-11ea-8ebf-21abaf0b8571.png">

All credits go to him!

**Comment by Conengmo** [comment] 2020-05-23 16:31
Oh great, I remember that we already merged a PR for that based on another ticket. That means we can close this one as well. Thanks for reporting back!

**Closed by Conengmo** 2020-05-23 16:31 UTC
