### ISSUE TITLE
Add timestamped function for ImageOverlay

### ISSUE THREAD

**Issue by xzenggit** [python-visualization/folium#1522] opened 2021-10-22 01:00 UTC
**Is your feature request related to a problem? Please describe.**

We have timestamp related plugins for heatmap, GeoJSON, and many others. However, we don't have timestamped ImageOverlay function. Is there a way of adding one? 

**Describe the solution you'd like**

Similar function as `folium.plugins.TimestampedGeoJson` or  `folium.plugins.TimestampedWmsTileLayers` should be fine.

Thanks!

**Comment by Conengmo** [comment] 2022-11-18 10:59
Duplicate of https://github.com/python-visualization/folium/issues/1007

**Closed by Conengmo** 2022-11-18 10:59 UTC
