### ISSUE TITLE
UndefinedError: 'Node' is undefined

### ISSUE THREAD

**Issue by Tee-A** [python-visualization/folium#1560] opened 2022-01-10 07:49 UTC
<img width="1123" alt="Screenshot 2022-01-10 at 8 50 46 AM" src="https://user-images.githubusercontent.com/31861767/148733050-771731cd-0bd6-4daa-bea7-a4d7cda9265a.png">
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
lat_0 = int(all_users_with_locations_2.latitudes.iloc[0])
lon_0 = int(all_users_with_locations_2.longitudes.iloc[0])

m = folium.Map(location=[lat_0, lon_0], zoom_start=4)

# Add markers

fields = ["name", "url", "Stack", "Country",
          "company", "address", "email",
          "bio", "followers", "following",
          "public_repos","id"]
aliases = ["Name", "URL", "Stack", "Country",
          "Company", "Address", "Email",
          "Bio", "Followers", "Following",
          "Number of Public Repos", "ID"]

citygeo = folium.features.GeoJson(
    all_users_with_locations_2,name="developers",
    tooltip=folium.features.GeoJsonTooltip(
         fields=fields, aliases=aliases, localize=True
    ),
).add_to(m)

# Add search 
citysearch = Search(
    layer=citygeo,
    geom_type="Point",
    placeholder="Search for a Country",
    collapsed=True,
    search_label="Country",
).add_to(m)


m


```
#### Problem description
I am trying to plot the map for my data using the above code but it keeps returning UndefinedError

[this should explain **why** the current behavior is a problem and what is the expected output.]

#### Expected Output

Expected output is a map showing all of the entries
<img width="1123" alt="Screenshot 2022-01-10 at 8 54 43 AM" src="https://user-images.githubusercontent.com/31861767/148733565-5507d40b-7231-4190-ba74-bd0462ad236d.png">

#### Output of ``folium.__version__``
'0.12.1.post1'
<img width="1123" alt="Screenshot 2022-01-10 at 8 49 12 AM" src="https://user-images.githubusercontent.com/31861767/148732936-c6adf3ce-e1ed-4c18-a7a9-a2c6e519693e.png">

**Comment by Conengmo** [comment] 2022-01-10 09:01
Just from looking at your issue report I don't immediately know what the issue is. Could you try to isolate the issue by:

- First just making a `Map`, see if that renders okay.
- Then add a `GeoJson`, without `GeoJsonTooltip`
- Then add the `GeoJsonTooltip` to `GeoJson`.
- Then finaly add `Search`.

At each step making sure the map renders okay. Then see at what step the issue starts.

**Comment by Tee-A** [comment] 2022-01-10 09:32
The issue starts from the point of adding the Geojson as shown in the screenshot below. The map doesn't render from then
![Screenshot 2022-01-10 at 10 31 41 AM](https://user-images.githubusercontent.com/31861767/148744094-27347417-96a5-4aec-b669-da50159a9e9b.png)

**Comment by Conengmo** [comment] 2022-01-10 09:41
If you use the GeoJSON data from our example notebook, you can test if it runs with that: https://github.com/python-visualization/folium/blob/main/examples/GeoJSON_and_choropleth.ipynb

If it doesn't there's probably something wrong with your installation or system. If it does run, there's probably an issue in your GeoJSON data.

**Comment by Tee-A** [comment] 2022-01-10 10:23
It does run, I guess the issue is with my geoJson data.. So I am converting a pandas dataframe to Geodatarame using the following sequence as in the image below
![Screenshot 2022-01-10 at 11 21 40 AM](https://user-images.githubusercontent.com/31861767/148750488-57d04341-b267-4ad9-b165-9562e6c4b226.png)

**Comment by Conengmo** [comment] 2022-01-10 10:31
I'm sorry, I can't really help you with that. I'd suggest taking a look at the example GeoJSON we have available, and try to find the issue in your data based on that.

I'm closing this issue as it's not an issue with folium.

**Closed by Conengmo** 2022-01-10 10:31 UTC
