### ISSUE TITLE
Osm (Openstreetmap) license links not working in iframe in Chrome

### ISSUE THREAD

**Issue by zvolsky** [python-visualization/folium#613] opened 2017-04-04 07:43 UTC
(maybe this is repeated or maybe this can be solved at the iframe attributes level; if so, I'm sorry)

Chrome reports "X-Frame-Options: sameorigin".
Bad is that Chrome ignores "X-Frame-Options: allow-from ..." header settings.

Following workaround in generated code works, but I am not sure if it is acceptable for all scenarios.
`html = html.replace('<div', '<base target="_parent"><div', 1)`

**Comment by ocefpaf** [comment] 2017-04-04 13:07
I just test it on my Chrome and everything worked. (Both on notebook and the a sand-alone HTML.)

What version of `Chrome` and `folium` are you using? (Closing this since I cannot reproduce it but we can keep discussing your case here.)

**Comment by zvolsky** [comment] 2017-04-05 07:54
Chromium Version 57.0.2987.98 built on Debian 9.0, running on Debian 9.0 (64-bit)

Example:

http://python-visualization.github.io/folium/quickstart.html#getting-started

links in the first map

-  Leflet works (??), 
- Openstreetmap will display nothing with following in Developer Tools:

Refused to display 'http://www.openstreetmap.org/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
www.openstreetmap.org/:1 GET http://www.openstreetmap.org/ net::ERR_BLOCKED_BY_RESPONSE
﻿

**Comment by ocefpaf** [comment] 2017-04-05 12:04
If you open in a new Window they all work but I think I know what the issue is. Let me try something here... Hold on...

**Comment by ocefpaf** [comment] 2017-04-05 20:35
> So I think with regard to Openstreetmap authors this is serious license corruption, in the folium homepage.

Why? Just because they don't allow their site to be opened in an IFrame? I really doubt it. Also, the site is accessible via a new Window.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
There is not much we can do on our side. Openstreemap could allow for iframe on its license at least.
Since they do not we could try to always open a new Windows. (That is what I am investigating now.)

**Closed by ocefpaf** 2017-04-05 20:35 UTC

**Comment by zvolsky** [comment] 2017-04-06 07:04
I'm sorry, I haven't understand that this is an openstreetmap.org restriction.
If so ... The link is there, everything is ok.
But because these are not links for usual work on the page but just to point to technologies and licenses, maybe opening always in new window would be good solution.

**Comment by ocefpaf** [comment] 2017-04-06 12:18
> maybe opening always in new window would be good solution

I agree that it is a good idea. Do you want to send a PR for that? I really don't have the time to look into this now.
