### ISSUE TITLE
examples not working

### ISSUE THREAD

**Issue by blis** [python-visualization/folium#72] opened 2015-01-10 19:42 UTC
When I run the Marker examples on https://github.com/python-visualization/folium, the html which is output has some malformed URLs in the head. For example, in the “mthood.html” example, the “http:” is missing in the following URLs:

href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"
src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"
href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"
href="//cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.Default.css"
href="//cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.css"
src="//cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/leaflet.markercluster-src.js"
src="//cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/leaflet.markercluster.js"

After I manually edit the html to include “http:" at the beginning of the URLs above, everything is happy. Same for the iconTest.html example.

I am running folium v0.1.3 and python3. 
I am using iPython notebook and Firefox on a Mac, although I don’t see how those would affect the html folium outputs.

Do I need to set some kind of folium config variable? Or is this a bug? Thanks!

PS The choropleth example “us_states.html” from https://github.com/python-visualization/folium also doesn’t work for me, but it’s not due to missing “http:” anywhere. I haven’t yet tracked down the cause, but what I get is a map of the US, a colorbar, but no unemployment data.

**Comment by ocefpaf** [comment] 2015-01-10 19:56
The template is correct, see http://fortawesome.github.io/Font-Awesome/get-started/.  You should not need the http.

Can you save the HTML, open a terminal window at the directory and type:

```bash
python3 -m http.server 8080
```

or (python2)

```bash
python -m SimpleHTTPServer 8080
```

Then click on the HTML and let me know if that works for you.

**Comment by blis** [comment] 2015-01-10 21:11
ocefpaf,
Good news and bad news:
1) Saving the html and serving it via python3 -m http.server 8080 works. Thanks!
2) However, opening the html file directly via the browser's File/Open File does not work. Must the html file be served by an http server to work? If so, is that an artifact of the CDN?
3) The us_state.html choropleth doesn't work either way.
thanks,
Bob

**Comment by ocefpaf** [comment] 2015-01-10 22:40
> 1) Saving the html and serving it via python3 -m http.server 8080 works. Thanks!

Good to know :wink:

> 2) However, opening the html file directly via the browser's File/Open File does not work. Must the html file be served by an http server to work? If so, is that an artifact of the CDN?

Not really.  This is how it is supposed to work.  Take a look at

https://developer.mozilla.org/en-US/Learn/Open_a_file_in_a_browser

for more information.  (If you find it too long go straight to the four bullet points on "**What we've learned**.")

> 3) The us_state.html choropleth doesn't work either way.

I cannot reproduce it here.  Can you be more specific.

**Comment by blis** [comment] 2015-01-11 22:14
Thanks for the pointer to the MDN post. I'm embarrassed I'd forgotten some of that!
Re the us_state.html choropleth, let me try some more to see if the problem is something I'm doing wrong.

**Comment by ocefpaf** [comment] 2015-01-12 11:27
Not a problem.  I am not a web expert myself.

I will close the issue.  You can re-open it if you find what is wrong with the choropleth example for you case.

**Closed by ocefpaf** 2015-01-12 11:27 UTC

**Comment by ianozsvald** [comment] 2015-07-10 21:14
Just to note - I've been struggling for some hours to get `map.create_map...` html rendered in a browser (and was wondering about the relative links in the generated html) until I saw this thread with `python -m http.server` and realised what was going on (and now it works - great!). I think it would greatly help new users if this snippet were included in the README to help folk get started! Many thanks for all your hard work.

**Comment by ocefpaf** [comment] 2015-07-10 21:23
@ianozsvald what version are you using?  We are enforcing `HTTPS` scheme now and folium should work just fine without serving the HTML.

**Comment by ianozsvald** [comment] 2015-07-10 22:13
@ocefpaf I'm using 1.4 (installed with `pip` today). I tried opening HTML in both Firefox 39 and Chrome 43.0.2357.132, using Linux Mint 17.2 (Ubuntu 14.04). I haven't tried with `head`, just 1.4.
