### ISSUE TITLE
strange problem with heat map rendering

### ISSUE THREAD

**Issue by bakerbd** [python-visualization/folium#411] opened 2016-04-05 02:12 UTC
I am trying to use the leaflet-heatmap.js plugin I saw was added to folium since the last time I looked at it.  I'm trying to visualize lets say surface pressure from a model output.  I normalize the pressure by the maximum pressure so the values lie between 0 and 1.  I cannot get it to work correctly.  

Here is the basics of the code.  

```python
mapa = folium.Map([40., -97.], tiles='stamentoner', zoom_start=4)
mapa.add_children(plugins.HeatMap(data.tolist(),radius=5,gradient=ff,max_zoom=10,blur=4))
mapa.save('test.html')
```

but the map just ends up a red blob

![test](https://cloud.githubusercontent.com/assets/17328569/14269403/48b47468-fab2-11e5-9f4c-a7aeab9767b9.jpg)

**Comment by bakerbd** [comment] 2016-04-05 16:38
Would it be possible to add the heatcanvas plugin? or quickly show how I can add a plugin?

**Comment by ocefpaf** [comment] 2017-08-25 21:25
> Would it be possible to add the heatcanvas plugin? or quickly show how I can add a plugin?

Are you referring to https://github.com/sunng87/heatcanvas ? If so we don't have dev time to invest but I would gladly review a PR.

> I am trying to use the leaflet-heatmap.js plugin I saw was added to folium since the last time I looked at it. I'm trying to visualize lets say surface pressure from a model output. I normalize the pressure by the maximum pressure so the values lie between 0 and 1. I cannot get it to work correctly.

Not sure if heatmap is the best option for a model result. Still, I cannot reproduce that without a [sscce](http://sscce.org/).

BTW, a lot has happen lately, so maybe the your issue was already fixed. Closing this but feel free to continue discuss here in case you have the SSCCE.

**Closed by ocefpaf** 2017-08-25 21:25 UTC
