### ISSUE TITLE
Feature Group item is checked on startup

### ISSUE THREAD

**Issue by testerx1** [python-visualization/folium#607] opened 2017-03-17 04:33 UTC
Feature Group item is checked on startup in Layer control in the html file. How to unchecked it on startup of the html file. Is there any full document of folium and example beside http://python-visualization.github.io/folium/?

**Comment by ocefpaf** [comment] 2017-03-17 12:26
That is a bug and we should address it. (It is probably duplicated but I cannot find the other issue now so I am keeping this open at the moment.)

**Comment by ocefpaf** [comment] 2017-09-21 13:58
Closing as a duplicate of #606

**Closed by ocefpaf** 2017-09-21 13:58 UTC
Labels: bug
