### ISSUE TITLE
Heatmap is visulized in the back of overlay image

### ISSUE THREAD

**Issue by alabrazi** [python-visualization/folium#1201] opened 2019-08-29 14:56 UTC
The problem is that the heatmap is visualized in the back of image overlay layer
![Aug-29-2019 17-54-18](https://user-images.githubusercontent.com/7549404/63951282-2794c380-ca86-11e9-90e7-541d82c55c73.gif)

**Comment by Conengmo** [comment] 2019-08-29 15:19
Hi @alabrazi, great gif, the issue is clear. I remember we had a discussion on that before. I suspect this is very similar. You can read it here: https://github.com/python-visualization/folium/issues/767 I'll include the solution listed there here as well:

> A quick dirty fix is to append the following to your html file: `<style>.leaflet-heatmap-layer{z-index:300 !important}</style>` Any z-index higher than 200 does the trick. You can add it to a custom template as described in #86.

Can you try that and let us know if it helped?

**Comment by Conengmo** [comment] 2019-09-21 07:02
I’ll close the issue since I think there’s not much we can do at the folium side.

**Closed by Conengmo** 2019-09-21 07:02 UTC

**Comment by JavierParada** [comment] 2020-10-19 04:34
Where should I include <style>.leaflet-heatmap-layer{z-index:300 !important}</style>?

**Comment by JavierParada** [comment] 2020-12-05 00:40
How can we solve this same issue with HeatMapWithTime instead of HeatMap?

**Comment by Dakcser** [comment] 2023-04-03 20:15
I quess better late then never. If anybody else has problem with HeatMapWithTime drawing data behind ImageOverlay. Instead of using above mentioned line of HTML code which tries to push heatmap layer foward. 

You can instead push ImageOverlay back with code ```<style>.leaflet-image-layer{z-index:-1 !important}</style>``` (Index -1 sets image back of the stack). 

![Sieppaa](https://user-images.githubusercontent.com/50385519/229616581-fbacbca9-a682-43f6-b78c-e4e907eab9d7.PNG)
