### ISSUE TITLE
CDN links are broken.

### ISSUE THREAD

**Issue by ColeTownsend** [python-visualization/folium#137] opened 2015-05-22 00:58 UTC
The links below work, the ones that folium by default builds with doesn't seem to work for me.

```html
   <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />


   <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

   <link rel="stylesheet" href="//rawgit.com/lvoogdt/Leaflet.awesome-markers/2.0/develop/dist/leaflet.awesome-markers.css">
   <script src="//rawgithub.com/lvoogdt/Leaflet.awesome-markers/2.0/develop/dist/leaflet.awesome-markers.js"></script>

   <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>

   <link rel="stylesheet" href="//birdage.github.io/Leaflet.awesome-markers/dist/leaflet.awesome.rotate.css">
   <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />

```

**Comment by ocefpaf** [comment] 2015-05-22 19:13
Which version of folium are you using?  I cannot reproduce your issue. I am closing this but feel free to re-open if you cannot get latest folium to work for you.

BTW: The latest folium version enforces HTTPS.  It should display nicely though on both HTTP/HTTPS schemes.

**Comment by ColeTownsend** [comment] 2015-05-22 19:13
Ah sorry man! It works fine when I spin up a local server, but just looking at it locally (i.e. as a file in safari) it doesn't work.

**Closed by ocefpaf** 2015-05-22 19:13 UTC

**Comment by ocefpaf** [comment] 2015-05-22 19:16
We used scheme agnostic URLs before and that was to support both HTTP and HTTPS.  But latest version enforces HTTPS and that should work on everything, including File:// scheme.

**Comment by ColeTownsend** [comment] 2015-05-22 23:40
Woo thanks!
