### ISSUE TITLE
How can I add permanent text on a folium map?

### ISSUE THREAD

**Issue by raidoz** [python-visualization/folium#214] opened 2015-10-20 16:33 UTC
I would like to permanently show some text(IDs) on or near circle markers? How can I do this?

**Comment by BibMartin** [comment] 2015-10-20 19:29
As suggested in #210, it may be possible to implement something looking like http://leaflet.github.io/Leaflet.label/

It's not available yet, but would it fit your need ?

**Comment by raidoz** [comment] 2015-10-21 13:02
This could work. Ideally I would still like to be able to get a separate pop-up with additional info. It's just that I need a way to identify the markers without clicking them.

**Comment by themiurgo** [comment] 2015-11-15 09:34
Closing this, duplicate of #210.

**Closed by themiurgo** 2015-11-15 09:34 UTC

**Comment by guyarad** [comment] 2018-06-25 10:32
#340
