### ISSUE TITLE
ColorMap Legend Position is always set to topRight. Change it by specifying the postion

### ISSUE THREAD

**Issue by muneebable** [python-visualization/folium#1734] opened 2023-03-06 18:55 UTC
**Is your feature request related to a problem? Please describe.**
I generated a Cholopreth Map using folium.Choropleth(), Now i t creates the Map perfectly and also add the legend to the topRight corner of the Map. There is no way to change the location of the Map to the topleft.

**Describe the solution you'd like**
I want to have an optional option in folium.Choropleth(), legend_postion, which is by_default set to topRIght, but we can be able to mention it to move topleft, bottomRight, bottomLeft etc.

**Additional context**
THis is the map, i created easily
![image](https://user-images.githubusercontent.com/3126387/223203967-285711b6-ca9a-4635-97c4-2517dd5326b7.png)

Here is the output I want, Here i change the HTML Code
![image](https://user-images.githubusercontent.com/3126387/223204095-81e4e2e0-6a49-4dba-b60b-52b734f529a9.png)

Is there any other way to do that? If the feature was not very useful.

**Comment by Conengmo** [comment] 2023-03-12 13:03
Thanks for your issue, I agree that would be a useful feature. It's not currently available. We already have an open issue about customizing the colorscale, so I'll close this one.

Duplicate of https://github.com/python-visualization/folium/issues/1605

**Closed by Conengmo** 2023-03-12 13:03 UTC
