### ISSUE TITLE
"[Vega Err] [object XMLHttpRequest]" error when trying to plot a vincent chart in folium based maps in python

### ISSUE THREAD

**Issue by alhaq** [python-visualization/folium#586] opened 2017-01-08 01:19 UTC
I'm experimenting with the folium library to plot charts in markers within maps. Doing this using the folium library in python. 

The code is pretty simple. As follows,

```python    
    import folium
    import vincent

    bar = vincent.Bar([1,2,3,4])
    popup1 = folium.Popup(max_width=1200,).add_child(folium.Vega(bar,width=500,height=500))
    m = folium.Map([47.3489, -124.708], zoom_start=5)
    folium.RegularPolygonMarker([47.3489, -124.708], popup=popup1).add_to(m)
    m.save("/home/map.html")
```

The code runs and creates the the html map. When I click on the marker, the block to render the chart comes up, but within it I see no chart. Also, before showing the chart, the browse throws an error saying 
[Vega Err] [object XMLHttpRequest]

Thanks in advance

**Comment by alhaq** [comment] 2017-01-10 04:32
i found the way to make this work. essentially all it needed was to save the json file to disk and read it abck using a json library read function.

**Comment by ocefpaf** [comment] 2017-03-06 18:38
Alright... Closing it them. BTW I cannot reproduce that in a notebook with the latest version.

**Closed by ocefpaf** 2017-03-06 18:38 UTC
