### ISSUE TITLE
Time slider disappears after click +- button to zoom on the map 

### ISSUE THREAD

**Issue by chen7572** [python-visualization/folium#841] opened 2018-04-03 21:49 UTC
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python

from folium.plugins import TimeSliderChoropleth

m = folium.Map(location=[40.45, -80], zoom_start=11)

g = TimeSliderChoropleth(
    tracts.to_json(),
    styledict=review_dict,

).add_to(m)

m

```
#### Problem description
I was able to use TimeSliderChoropleth plugin to make an interactive map to show changes over time, but as soon as I use the +- sign on the map to zoom in and out on the map, the slider disappears and I cannot get it back! Had similar issue when testing the example case given on Github. Any advice on how to work around this? Thank you very much!

**Comment by Conengmo** [comment] 2018-04-09 08:06
I tried to reproduce your problem using [the example case](http://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/TimeSliderChoropleth.ipynb) but wasn't able to. Could you share some more details on your setup, are you in a Jupyter Notebook? Which browser?

**Comment by chen7572** [comment] 2018-04-09 21:12
Thank you for follow up! I am using Jupyter Notebook on Chrome to make the plot.

**Comment by TatianaSnauwaert** [comment] 2020-05-29 11:58
Hi! 
I have the same issue (timeslider disappears when I zoom).
I am working in Chrome on Kaggle. I tested it in Firefox, works fine, so probably the issue is the browser.
Here is my notebook if needed:
https://www.kaggle.com/tatianasnwrt/visualizing-air-quality-in-budapest-folium?scriptVersionId=35041811

**Comment by Conengmo** [comment] 2020-05-29 12:12
I went to that url in Chrome but didn't encounter the same issue.

Maybe this is related to https://github.com/python-visualization/folium/issues/1301 ?

**Comment by Conengmo** [comment] 2020-08-26 13:36
Yes I believe these are the same problems. The map fills 100 % of its container, and then we add the slider on top, expanding beyond the size of the container. Something like that.

**Comment by Conengmo** [comment] 2022-11-25 11:31
Let's close this one in favor of https://github.com/python-visualization/folium/issues/1301

**Closed by Conengmo** 2022-11-25 11:31 UTC
Labels: bug, jupyter
