### ISSUE TITLE
Maximum number of popups or bug?

### ISSUE THREAD

**Issue by jmaralcZ** [python-visualization/folium#1263] opened 2020-02-13 20:24 UTC
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
import folium

import folium
number_of_markers = 1610 #Work!
# number_of_markers = 1611 #Will not work! not render
m = folium.Map()
for i in range(number_of_markers):
    mark = folium.CircleMarker(location=(31,31),popup='here')
    mark.add_to(m)
display(m)

```
#### Problem description
Hi, I have a regular dataset size of ~5000 and I was trying to add popups to each one of the points to provide explanations about the point. I could not do it; I was able to attach the popup but they are not rendered when I want to display the map. 
The example above is a simple example.

My folium version is 0.10.0

So my question is whether this is a bug or is a limit of folium? If it is a bug, is there any workaround that you know to have more popups?

Thanks

**Comment by jmaralc** [comment] 2020-02-14 14:08
Hi guys, me again but from different account. Just a clarification about the previous. The issue happened testing it with Chrome Version 79.0.3945.88 (Official Build) (64-bit), with Firefox 72.0.1 (64-bit) works absolutely fine. 
Any idea on the difference of performance between browsers?
Cheers, and thanks.

**Comment by fullonic** [comment] 2020-02-14 18:16
Hi, I didn't run your code, but if it works with Firefox and not with Chrome maybe is being fixed with PR #812.

**Comment by Conengmo** [comment] 2020-02-17 09:37
@jmaralcZ could you try installing branca from the git master branch? See if that solves your issue? branca is a library that is sort of part of folium.

`pip install git+https://github.com/python-visualization/branca`

I'm assuming this is a duplicate of #812 as @fullonic mentioned. We can reopen if it turns out not to be the case.

**Closed by Conengmo** 2020-02-17 09:37 UTC

**Comment by jmaralcZ** [comment] 2020-02-17 10:40
> pip install git+https://github.com/python-visualization/branca

@Conengmo I confirm that It worked with installing directly from the repo. Thanks!

**Comment by Conengmo** [comment] 2020-02-17 11:20
That's good to hear, thanks for reporting back!
