### ISSUE TITLE
HTML legend for feature group

### ISSUE THREAD

**Issue by rgox** [python-visualization/folium#1478] opened 2021-06-04 08:06 UTC
#### Please add a code sample or a nbviewer link, copy-pastable if possible

folium_FeatureGroup.get_root().html.add_child(folium.Element(script + css))

create this error : 
AttributeError: 'FeatureGroup' object has no attribute 'html'

and if I remove .html my legend doesn't appear

```
#### Problem description

I am looking to add an HTML legend at the bottom corner of each layer. The legend will be different per layer.

I can add an HTML legend to the base map using map.get_root().html.add_child(<html>), however this will only display the same text for all layer. I am looking instead for a method to attach html to a feature group, ie, something like feature_group.get_root().html.add_child(<html>)

**Comment by SandraMartinezGutierrez** [comment] 2022-08-01 23:53
Excuse me, I'm having the same problem, were you able to solve it?

**Comment by Conengmo** [comment] 2022-11-18 11:54
Duplicate of https://github.com/python-visualization/folium/issues/1079

**Closed by Conengmo** 2022-11-18 11:54 UTC
