### ISSUE TITLE
HOW can I set the map to always show popup?

### ISSUE THREAD

**Issue by Michael728** [python-visualization/folium#593] opened 2017-02-28 09:19 UTC
I want to see the popup to know every name of the point, how to show them?

**Comment by ocefpaf** [comment] 2017-03-06 19:31
This was not implemented yet. I am closing as a duplicate of https://github.com/python-visualization/folium/issues/210

**Closed by ocefpaf** 2017-03-06 19:31 UTC

**Comment by tshuangteng** [comment] 2022-04-10 12:00
you can use the following code, with tooltip
```
tooltip = folium.Tooltip(permanent=True, text='<b style="white-space: nowrap">text content......</b>')
```
