### ISSUE TITLE
VegaLite Graph not showing colours in legend

### ISSUE THREAD

**Issue by Vulmest** [python-visualization/folium#1222] opened 2019-11-10 07:54 UTC
#### Please add a code sample or a nbviewer link, copy-pastable if possible

```python
import altair as alt
import pandas as pd
import folium

m = folium.Map(
    location=[45.372, -121.6972],
    zoom_start=12,
    tiles='Stamen Terrain'
)

# Test data can be found here: 
# https://1drv.ms/u/s!Ag4bn1xbLefBhO9cP0zIPxnwOL27xg?e=7oxbk6

source = pd.read_csv("test_data.csv")
base = alt.Chart(source).mark_line().encode(
alt.X('TIME_PER_HOUR:O', axis=alt.Axis(title='Hour')),
alt.Y('TOTAL_TAP_VOLUME', axis=alt.Axis(title='Tap Volume')),
color=alt.Color('DATA_TYPE', legend=alt.Legend(title="Day Type"))
)

vega = folium.features.VegaLite(graph, width='100%', height='100%')
graph_popup = folium.Popup()  # Create a popup
vega.add_to(graph_popup)  # Add graph to popup

tooltip = 'Click me!'
folium.Marker([45.3311, -121.7113], popup=graph_popup, tooltip=tooltip).add_to(m)

m
```
#### Problem description
The graph is not correctly showing the legend colours, the colours do not appear at all
![image](https://user-images.githubusercontent.com/9456670/68540771-35de5480-03d2-11ea-8ac7-5e8e239750f4.png)

#### Expected Output
![image](https://user-images.githubusercontent.com/9456670/68540751-f9125d80-03d1-11ea-965c-d4fd890b071e.png)

#### Output of ``folium.__version__``
0.10.0

**Comment by Conengmo** [comment] 2019-11-11 11:28
I don't think this is an issue with folium. Our VegaLite code just accepts any data and dumps it in the HTML. So I'm assuming the issue is in VegaLite or in your code. I'm closing the issue but feel free to add any more info or findings here.

Hint: it might be good to check in the html generated by folium what version of VegaLite was embedded. Look for `https://cdn.jsdelivr.net/npm/vega-lite` or `https://cdnjs.cloudflare.com/ajax/libs/vega-lite`. If no version is defined in the data we assume version 2.

**Closed by Conengmo** 2019-11-11 11:28 UTC
