### ISSUE TITLE
unexpected result after changing parameter crs (Coordinate Reference Systems)

### ISSUE THREAD

**Issue by GuodongZhu** [python-visualization/folium#1266] opened 2020-03-05 02:19 UTC
The default Coordinate Reference Systems in folium is WGS84/Pseudo-Mercator/EPSG3857.

I found that folium also supports EPSG4326. When I set crs parameter equal to EPSG4326, the circle I drew around Dallas, TX now appear in the Atlantic ocean, which is way off.

```python
map = folium.Map(location=[32, -97], zoom_start=7, crs= 'EPSG4326' )
folium.Circle( location=[32,-97], radius=40 * 1000, fill=False).add_to(map)
map.save("test.html")
```

My folium.__version__ is 0.10.1.

**Comment by Conengmo** [comment] 2020-03-05 09:10
This is a duplicate of #1161 I think. As said before there, the tileset we're using by default (OpenStreetMap) needs EPSG3857. If you change the CRS, those tiles won't map correctly. 

The `crs` parameter in `folium.Map` should correspond with the tileset that you are using. You shouldn't change its value without also selecting a different tileset.

**Closed by Conengmo** 2020-03-05 09:10 UTC
