### ISSUE TITLE
Choropleth legends being part of the layer

### ISSUE THREAD

**Issue by ox-baloo** [python-visualization/folium#1052] opened 2019-01-13 08:07 UTC
#### Please add a code sample or a nbviewer link, copy-pastable if possible

This is how I created and added the folium.Choropleth layers to the folium.Map object (self.map is a default folium.Map object)

```python
        folium.Choropleth(geo_data=self.geo_json,
                     data=self.map_data,
                     columns=[self.CODE_COL,self.SCORE_COL],
                     key_on='feature.properties.' + self.code_name,
                     fill_color=self.color,
                     fill_opacity=0.6,
                     line_opacity=0.2,
                     bins=self.scale,
                     legend_name=self.legend_label,
                     name=name,
                     nan_fill_color='purple',
                     show=show).add_to(self.map)
```
This is how I added folium.LayerControl and saved the file

```python
        folium.LayerControl(collapsed=False).add_to(self.map)
        self.map.save(self.out_file)
```
#### Problem description

I created a folium.Map with two folium.Choropleth objects added to it as overlays, so that someone viewing the .html file could choose which choropleth map they would like to see using the LayerControl. When the layers were deselected the choropleth layers were removed from the screen but the legend stayed.

I found this behaviour confusing as, when a choropleth layer was deselected the legend remained on the screen, I would expect the legends to belong to the layers on the map and appear and disappear as layers were selected/deselected.

#### Expected Output

The legends for a folium.Choropleth object should disappear when the folium.Choropleth layer is deselected from the layer control box.

#### Output of ``folium.__version__``
0.7.0

**Comment by emc5ud** [comment] 2019-05-20 19:00
Even in maps with a single choropleth, being able to toggle the legend's visibility along with the choropleth helps reduce visual clutter.

**Comment by julianaddison** [comment] 2020-02-26 05:15
Hi, any chance if this has been fixed or if there's a workaround that anyone's aware of, I would be most grateful. Thanks.

**Comment by kylenguyen245** [comment] 2020-03-03 20:43
Much appreciate if this problem is solved as well! Thanks!!!

**Comment by emc5ud** [comment] 2020-03-04 00:18
You can do a hacky workaround by saving your map to html and adding the following lines:

```
 map.on('overlayadd', function (eventLayer) {
        $('.legend').show();
    });
    map.on('overlayremove', function (eventLayer) {
        $('.legend').hide();
    });
```
This will only work in specific cases though (one choropleth as your only overlay and only 1 legend object)

**Comment by kylenguyen245** [comment] 2020-03-04 14:33
Hey emc5ud, thanks for your reply. I wonder if there is anyway to just remove the legend completely within Python script? I see a thread mentioned about this and tried to implemented it but it doesn't work. Do you have any thoughts on this?
![image](https://user-images.githubusercontent.com/61759415/75889594-c3ffa000-5df2-11ea-8c8e-3d6bf464b751.png)

**Comment by jjbenes** [comment] 2020-04-01 22:52
@julianaddison  The Python method @kylenguyen245  mentioned does work in principle. Delete color_map children outside of the loop. Hope this helps.

@kylenguyen245 I sometimes delete the legend (color maps) because the numerical labels overlap one another. Do you know whether there's a way to use fewer labels than there are bins to avoid overlapping labels (see picture)? 
![overlapping labels](https://user-images.githubusercontent.com/62985029/78194005-c88a9900-7430-11ea-9c74-2e49ab6e0f6b.png)


```
def folium_del_legend(choropleth: folium.Choropleth):
  """A hack to remove a choropleth legend.
  
  The choropleth color-scaled legend sometimes looks too crowded. Until there is an
  option to disable the legend, use this routine to remove any color map children
  from the choropleth.
  
  Args:
    choropleth: Choropleth objected created by `folium.Choropleth()`
    
  Returns:
    The same object `choropleth` with any child whose name starts with
    'color_map' removed.
  """
  del_list = []
  for child in choropleth._children:
    if child.startswith('color_map'):
      del_list.append(child)
  for del_item in del_list:
    choropleth._children.pop(del_item)
  return choropleth

m = folium.Map(...)
folium_del_legend(
    folium.Choropleth(...)).add_to(m)
```

**Comment by AhadMomin** [comment] 2021-01-29 09:00
does anyone have a fixed for this instead of hiding the legend? I have a choropleth with a lot of layers and actually need the colormap to be displayed for each of my layer being selected :(. would really appreciate help!

**Comment by StevePuts** [comment] 2021-07-02 20:08
I could also use a solution for this. I have maps with 40 layers.

**Comment by jomccall** [comment] 2021-09-23 20:05
Same

**Comment by Malmurrani** [comment] 2021-09-23 22:38
Hi,
any help 
trying to remove the color scale or at least link one color scale to each layer.  rather than showing all maps scales at the same time. thanks

**Comment by Mah-88** [comment] 2022-02-03 12:36
Hi,
Could anyone solve this issue and display each legend according to the relevant layer? 
Many thanks

**Comment by wwright21** [comment] 2022-10-21 15:44
Looking for a solution here. I've got multiple choropleth layers and would like for each choropleth's legend to be part of the layer, such that selecting Choropleth 1 would show its corresponding legend, but then selecting Choropleth 2 would remove the first legend and show the legend corresponding to this second layer. It doesn't make much sense to continue showing the legend for Choropleth 1 layer even when it's turned off.

**Comment by Conengmo** [comment] 2022-11-25 11:01
Turns out this is actually a duplicate of https://github.com/python-visualization/folium/issues/450

**Closed by Conengmo** 2022-11-25 11:01 UTC
Labels: bug
