### ISSUE TITLE
HeatMapWithTime show map only (python 3.6.9, folium 0.10.1)

### ISSUE THREAD

**Issue by ying951** [python-visualization/folium#1305] opened 2020-04-21 06:35 UTC
I have been using the HeatMapWithTime on Apr 18, but it failed on Apr 19 after I install imageio and ffmpeg. The web page shows nothing without base map. I don't kown if it's becuase I accidentally update it? I then uninstalled all the newly installed plugins but still couldn't solve this problem.
I used farisnanosoft's method to replace the URL for leaflet.timedimension.min.js. The slider appeared but still no heatmap. 
I also try to visit the URL: https://rawcdn.githack.com/nezasa/iso8601-js-period/master/iso8601.min.js and https://rawcdn.githack.com/python-visualization/folium/master/folium/templates/pa7_hm.min.js, none of them can be accessed.
My python version is 3.6.9 and Folium is 0.10.1. Please help me and gvie a solution.

_Originally posted by @ying951 in https://github.com/python-visualization/folium/issues/1221#issuecomment-616952859_

**Comment by Conengmo** [comment] 2020-04-21 07:35
Hi, can you share a code snippet that reproduces your problem? Please make sure it contains data (snippet) so we can run it. Can you check your browser console if there are any error messages there? Could you try installing folium from our git master branch?

**Comment by ying951** [comment] 2020-04-21 08:10
Thank you for your reply. My code is as follow:
----------------------------------------------------------
# input NETCDF
nc_obj=Dataset(url+'data/modeling/wrfout_d01_2019-04-25_18_00_00')
pm2_5=(nc_obj.variables['PM2_5_DRY'][:])
pm10=(nc_obj.variables['PM10'][:])
so2=(nc_obj.variables['so2'][:])
no2=(nc_obj.variables['no2'][:])
no=(nc_obj.variables['no'][:])
o3=(nc_obj.variables['o3'][:])
co=(nc_obj.variables['co'][:])
lat=(nc_obj.variables['XLAT'][:])
lon=(nc_obj.variables['XLONG'][:])
Times=(nc_obj.variables['Times'][:])
nox=no2+no

# input JSON
with open(url+"map/world.geo.json",'r') as load_f:
        World_dict = json.load(load_f)

levels = 20

# Function to convert the data of the dataframe
def make_data(data_var,levels, map_name, color_name):
    print('<'+map_name+'>')
    print('  Data pre-processing...')
    vmin = data_var[:,0,:,:].min()
    vmax = data_var[:,0,:,:].max()
    data=np.zeros(shape=(len(Times), len(lat[1,:,:].flatten()), 3))
    index=[]
    for i in range(len(Times)):
        weight=data_var[i,0,:,:].flatten()
        lat_f=lat[i,:,:].flatten()
        lon_f=lon[i,:,:].flatten()
        data[i,:,0]=lat_f
        data[i,:,1]=lon_f
        data[i,:,2]=weight/vmax
#        ind=time.strptime(str(Times[i],'utf-8'),"%Y-%m-%d_%H:%M:%S")
        ind=str(Times[i],'utf-8')
        index.append(ind)
    print(data.shape)
    data=data.tolist()
    cmm = cm.get_cmap(color_name,levels)
    cmk = np.linspace(vmin/vmax, 1.0, num=levels)
    colors=cmm(range(levels))
    colors_t = tuple(tuple(x) for x in colors)
    cm_dict={}
    for i in range(0,levels):
        cm_dict[cmk[i]]=str(matplotlib.colors.to_hex(colors[i,:], keep_alpha=True))
        
#    print(cm_dict)
    cbar = branca.colormap.LinearColormap(colors_t, vmin=vmin, vmax=vmax).to_step(levels)       
    cbar.caption = map_name
    cbar.add_to(m)
    return(data,index,cm_dict,cbar)

def make_heatmap(data,index,map_name,cm_dict,cbar):
    print('  Making HeatMap...')
    fg = HeatMapWithTime(
            data=data,
            index=index,
            name=map_name,
            radius=1.1,
            min_opacity=0.,
            max_opacity=0.8,
            scale_radius=True,
            gradient=cm_dict,
            auto_play=False,
            position='bottomleft',
            overlay=False,
            show=True
            ).add_to(m)
    m.add_child(BindColormap(fg, cbar))
    print('  Done.')
    return(fg)

def make_additional(data,map_name,cm_dict,cbar):
    print('  Making HeatMapAdditional...')
    fg = HeatMapWithTimeAdditional(
            data=data,
            name=map_name,
            radius=1.1,
            min_opacity=0.,
            max_opacity=0.8,
            scale_radius=True,
            gradient=cm_dict,
            overlay=False,
            ).add_to(m)
    print('  Done.')
    m.add_child(BindColormap(fg, cbar))
    return(fg)

def make_map(data_var,levels, map_name, color_name):
    data,index,cm_dict,cbar = make_data(data_var,levels, map_name, color_name)
    fg = make_heatmap(data,index,map_name,cm_dict,cbar)
    return(fg)

def make_mapadd(data_var,levels, map_name, color_name):
    data,index,cm_dict,cbar = make_data(data_var,levels, map_name, color_name)
    fg = make_additional(data,map_name,cm_dict,cbar)
    return(fg)



# ***** MAP *****
print(">> Drawing ...")
m = folium.Map([38., 100.], 
        tiles=None,
        zoom_start=6,
        )

#P = folium.map.CustomPane(name="mapGD", z_index=600, pointer_events=False).add_to(m)

folium.TileLayer(
        tiles='http://webst02.is.autonavi.com/appmaptile?style=6&x={x}&y={y}&z={z}',
        control=False,
        zoom_start=6,
        min_zoom=1,
#        pane='mapGD',
        attr='Belt & Road'
        ).add_to(m)


fg_pm2_5 = make_map(pm2_5, levels, 'PM2.5_predict','plasma')
fg_pm10 = make_mapadd(pm10, levels, 'PM10_predict', 'viridis')
fg_so2 = make_mapadd(so2, levels, 'SO2_predict', 'plasma')
fg_nox = make_mapadd(nox, levels, 'NOx_predict', 'inferno')
fg_o3 = make_mapadd(o3, levels, 'O3_predict', 'gist_earth')
fg_co = make_mapadd(co, levels, 'CO_predict', 'terrain')

# Map the Country bounds from json
WorldMap = folium.GeoJson(
    World_dict,
    name='World_Map',
    style_function=lambda x: {
         'color': 'white',
         'weight': 0.5,
         'opacity': 1.,
         'fillOpacity': 0.
          }
    ).add_to(m)

folium.LayerControl(position='bottomleft', collapsed=False, sortLayers=False).add_to(m)

folium.plugins.Fullscreen(
            position='topright',
            title='Expand me',
            title_cancel='Exit me',
            force_separate_button=True
            ).add_to(m)

print(">> Save index.html ...")

m.save(url+'index.html')

print(">> End ")
---------------------------------------------------------
data and times as follow:
---------------------------------------------------------
[[[ 8.71999931e+00 -6.27999878e+00  1.23823729e-05]
  [ 8.71999931e+00 -5.55999756e+00  1.41246437e-05]
  [ 8.71999931e+00 -4.83999634e+00  5.15037073e-06]
  ...
  [ 6.12800026e+01  1.34839996e+02  8.71601733e-05]
  [ 6.12800026e+01  1.35559998e+02  7.81530252e-05]
  [ 6.12800026e+01  1.36279999e+02  7.70101105e-05]]

 [[ 8.71999931e+00 -6.27999878e+00  2.23065072e-05]
  [ 8.71999931e+00 -5.55999756e+00  2.54237657e-05]
  [ 8.71999931e+00 -4.83999634e+00  8.89739476e-06]
  ...
  [ 6.12800026e+01  1.34839996e+02  9.09287919e-05]
  [ 6.12800026e+01  1.35559998e+02  8.17209366e-05]
  [ 6.12800026e+01  1.36279999e+02  8.05298041e-05]]

 [[ 8.71999931e+00 -6.27999878e+00  2.23711377e-05]
  [ 8.71999931e+00 -5.55999756e+00  2.54549268e-05]
  [ 8.71999931e+00 -4.83999634e+00  8.91218133e-06]
  ...
  [ 6.12800026e+01  1.34839996e+02  9.50488175e-05]
  [ 6.12800026e+01  1.35559998e+02  8.52620506e-05]
  [ 6.12800026e+01  1.36279999e+02  8.40190842e-05]]

 ...

 [[ 8.71999931e+00 -6.27999878e+00  4.96608982e-06]
  [ 8.71999931e+00 -5.55999756e+00  5.60228546e-06]
  [ 8.71999931e+00 -4.83999634e+00  1.97021200e-06]
  ...
  [ 6.12800026e+01  1.34839996e+02  8.61755950e-07]
  [ 6.12800026e+01  1.35559998e+02  1.26998842e-04]
  [ 6.12800026e+01  1.36279999e+02  1.30810076e-04]]

 [[ 8.71999931e+00 -6.27999878e+00  5.16199725e-06]
  [ 8.71999931e+00 -5.55999756e+00  5.79941707e-06]
  [ 8.71999931e+00 -4.83999634e+00  2.03290801e-06]
  ...
  [ 6.12800026e+01  1.34839996e+02  8.63428340e-07]
  [ 6.12800026e+01  1.35559998e+02  1.32458212e-04]
  [ 6.12800026e+01  1.36279999e+02  1.34784394e-04]]

 [[ 8.71999931e+00 -6.27999878e+00  1.12095231e-05]
  [ 8.71999931e+00 -5.55999756e+00  1.25655142e-05]
  [ 8.71999931e+00 -4.83999634e+00  4.48923674e-06]
  ...
  [ 6.12800026e+01  1.34839996e+02  8.69384394e-07]
  [ 6.12800026e+01  1.35559998e+02  1.37560593e-04]
  [ 6.12800026e+01  1.36279999e+02  1.38489544e-04]]]
.............................................................................................................................
2019-04-25_18:00:00     
2019-04-25_19:00:00     
2019-04-25_20:00:00     
2019-04-25_21:00:00     
2019-04-25_22:00:00     
2019-04-25_23:00:00     
2019-04-26_00:00:00     
2019-04-26_01:00:00     
2019-04-26_02:00:00
2019-04-26_03:00:00
2019-04-26_04:00:00
2019-04-26_05:00:00
2019-04-26_06:00:00
2019-04-26_07:00:00
2019-04-26_08:00:00
2019-04-26_09:00:00
2019-04-26_10:00:00
2019-04-26_11:00:00
2019-04-26_12:00:00
2019-04-26_13:00:00
2019-04-26_14:00:00
2019-04-26_15:00:00
2019-04-26_16:00:00
2019-04-26_17:00:00
---------------------------------------------------------
In addition, I tested the online examples
---------------------------------------------------------
import folium
import folium.plugins as plugins
import numpy as np

np.random.seed(3141592)
initial_data = (
    np.random.normal(size=(100, 2)) * np.array([[1, 1]]) +
    np.array([[48, 5]])
)

move_data = np.random.normal(size=(100, 2)) * 0.01

data = [(initial_data + move_data * i).tolist() for i in range(100)]

weight = 1  # default value
for time_entry in data:
    for row in time_entry:
        row.append(weight)

m = folium.Map([48., 5.], tiles='stamentoner', zoom_start=6)

hm = plugins.HeatMapWithTime(data)

hm.add_to(m)

m.save('/mnt/e/html/heat.html')

---------------------------------------------------------
but it didn't show the heapmap on my computer.

**Comment by ying951** [comment] 2020-04-21 08:19
My computer has been updated and then the heatmap is no longer there.  I used the ubantu system in win10, will it affect?

**Comment by CaoHua1203** [comment] 2020-04-22 03:39
I am facing similar cases.

When open the files which looks normal last week, but now  no marker is shown, only a blank map there.

Thanks.

**Comment by Conengmo** [comment] 2020-04-23 06:55
I can't reproduce your issue, heatmapwithtime still works for me.

@ying951 you mentioned you cannot access https://rawcdn.githack.com/nezasa/iso8601-js-period/master/iso8601.min.js and https://rawcdn.githack.com/python-visualization/folium/master/folium/templates/pa7_hm.min.js ? What do you mean with that? If you open these urls in your browser, what happens?

Can you check your browser console and share any error messages you see there?

**Comment by ying951** [comment] 2020-04-24 06:34
I get the error messages as follows: 
----------------------------------------------------------------
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
iso8601.min.js:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
pa7_hm.min.js:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
leaflet-heatmap.js:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
index.html:57 Uncaught ReferenceError: HeatmapOverlay is not defined
    at initialize (index.html:57)
    at new i (leaflet.js:5)
    at index.html:599
---------------------------------------
And when I access https://rawcdn.githack.com/python-visualization/folium/master/folium/templates/pa7_hm.min.js, I get:
----------------------------------------
Object
94Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure image '<URL>'. This content should also be served over HTTPS.
errsug7_new.js:1 Object "sct height"
76640e17d4a36693.js:1 -- readyToGetNews -- readyToGetNews -- readyToGetNews --
errsug7_new.js:1 Object "sct height"
76640e17d4a36693.js:1 true
76640e17d4a36693.js:1 -- getSpecialData -- getSpecialData -- getSpecialData --
76640e17d4a36693.js:1 -- renderNews -- renderNews -- renderNews -- renderNews --
76640e17d4a36693.js:1 本次数据请求方式：loadMore
76640e17d4a36693.js:1 文字链广告条数：1
errsug7_new.js:1 Object "sct height"
DevTools failed to parse SourceMap: https://cjhd.mediav.com/js/news_feed_video.js.map
--------------------------------------
Thank you very much for your sincere help. Hope the above information is helpful.

**Comment by Conengmo** [comment] 2020-04-24 07:06
It sounds like you cannot load the Javascript resources we host at rawcdn.githack.com.

Those are some weird error messages though. Are those all related to loading that rawcdn.githack.com resource? I hope not.

Is maybe rawcdn.githack.com blocked for you? It might we worth trying a computer on another network.

**Comment by ying951** [comment] 2020-04-24 07:14
I have this problem at home and at work. Is there something wrong with my computer upgrading itself? Should I try another computer?

**Comment by Conengmo** [comment] 2020-04-24 07:29
Trying another computer sounds like a good idea.

**Comment by wetfire2k** [comment] 2020-05-01 13:29
Hi guys i'm having a similar issue on colab. I think there is an error on imported link.
I'm supposing you are referring to an "http" url insted of an "https".
Give a look at "mixed contents" error messages.

**Comment by wetfire2k** [comment] 2020-05-01 13:33
Sorry now I see that the file on codebase here in git is ok. So I suppose colab refers to an old version of lib.

**Comment by khvilaboa** [comment] 2020-05-03 21:13
I'm having the same issue in colab, and also see some affected tutorials (at least in my browser, adblocker disabled). An example [here](https://www.kaggle.com/daveianhickey/how-to-folium-for-maps-heatmaps-time-analysis). Simple HeatMap works, though.

In the linked tutoial there are some (maybe related) errors in the terminal:
![error_log](https://i.ibb.co/bPxBndj/Screenshot-from-2020-05-03-17-09-25.png)

**Comment by Conengmo** [comment] 2020-05-23 09:54
I believe this issue and #1307 are caused by the same issue. I'm closing this one. In short, we'll have to move to another CDN that has better global reach.

**Closed by Conengmo** 2020-05-23 09:54 UTC
