### ISSUE TITLE
[FeatureRequest ?] Show / Hide Selected Overlays

### ISSUE THREAD

**Issue by odovad** [python-visualization/folium#690] opened 2017-08-28 14:06 UTC
Hi, 

If I have multiple overlays and want to generate the map with only one of them selected.
How to do it, is it possible ?

Thanks

**Comment by ocefpaf** [comment] 2017-08-28 14:10
Closing as a duplicate of https://github.com/python-visualization/folium/issues/606

PRs welcome :wink:

**Closed by ocefpaf** 2017-08-28 14:10 UTC
