### ISSUE TITLE
Progressively annotating a map in ipython notebook

### ISSUE THREAD

**Issue by psychemedia** [python-visualization/folium#44] opened 2014-07-11 12:40 UTC
If I take the 

```
import folium
folium.initialize_notebook()
``` 

route to using folium in an IPython notebook, if I create a map and preview it in one cell, then annotate the map and try to view it from another cell, I get the error:

```
Javascript error adding output!
Error: Map container is already initialized.
```

However, if I use the old inline_map/iframe approach, as in http://nbviewer.ipython.org/gist/psychemedia/c1ac132946fa120cad91 for example, I can drop iframes containing increasingly layered maps into multiple cells.

In the notebook context used for investigation or teaching purposes, it would be handy to be able to build up maps a cell at a time, previewing them after each cell?

**Comment by ocefpaf** [comment] 2015-08-04 17:30
> In the notebook context used for investigation or teaching purposes, it would be handy to be able to build up maps a cell at a time, previewing them after each cell?

Indeed.  The `initialize_notebook()` needs an overhaul.  

Since this is a duplicate of #135. I am closing this.

**Closed by ocefpaf** 2015-08-04 17:30 UTC
Labels: bug

**Comment by ocefpaf** [comment] 2015-08-19 16:29
Hopefully PR #190 will take care of that.  See some examples at: http://nbviewer.ipython.org/github/ocefpaf/folium_notebooks/tree/master/
